apiVersion: v1
items:
- apiVersion: upgrade.cattle.io/v1
  kind: Plan
  metadata:
    annotations:
      meta.helm.sh/release-name: local-managed-system-agent
      meta.helm.sh/release-namespace: cattle-system
      objectset.rio.cattle.io/id: default-local-managed-system-agent-cattle-fleet-local-system
      upgrade.cattle.io/digest: spec.upgrade.envs
    creationTimestamp: "2022-03-06T22:50:13Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      objectset.rio.cattle.io/hash: a5c96e7b968940534a2e095661b8734ee2eea04f
    managedFields:
    - apiVersion: upgrade.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
            f:upgrade.cattle.io/digest: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
            f:objectset.rio.cattle.io/hash: {}
        f:spec:
          .: {}
          f:concurrency: {}
          f:nodeSelector:
            .: {}
            f:matchExpressions: {}
          f:serviceAccountName: {}
          f:tolerations: {}
          f:upgrade:
            .: {}
            f:envFrom: {}
            f:envs: {}
            f:image: {}
          f:version: {}
      manager: fleetagent
      operation: Update
      time: "2022-03-06T22:50:13Z"
    - apiVersion: upgrade.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:latestHash: {}
          f:latestVersion: {}
      manager: system-upgrade-controller
      operation: Update
      time: "2022-03-07T22:11:31Z"
    name: system-agent-upgrader
    namespace: cattle-system
    resourceVersion: "14658774"
    uid: 427386a3-2a7a-4a9a-9cc0-6dc870aba52d
  spec:
    concurrency: 10
    nodeSelector:
      matchExpressions:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
    serviceAccountName: system-agent-upgrader
    tolerations:
    - operator: Exists
    upgrade:
      envFrom:
      - secretRef:
          name: stv-aggregation-local-4ca379b917fb
      envs:
      - name: CATTLE_ROLE_WORKER
        value: "true"
      image: rancher/system-agent
    version: v0.1.1-suc
  status:
    conditions:
    - lastUpdateTime: "2022-03-22T23:49:24Z"
      reason: Version
      status: "True"
      type: LatestResolved
    latestHash: 79508c71b312ccd2bf49c5c23afe023d15e59287dede6d6bc75a967b
    latestVersion: v0.1.1-suc
kind: List
metadata:
  continue: "null"
  resourceVersion: "14659045"
