apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: driver.longhorn.io
    creationTimestamp: "2022-03-06T22:52:42Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2022-03-08T00:02:32Z"
    finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/driver-longhorn-io
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/provisioned-by: {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
          f:csi:
            .: {}
            f:driver: {}
            f:fsType: {}
            f:volumeAttributes:
              .: {}
              f:baseImage: {}
              f:fromBackup: {}
              f:migratable: {}
              f:numberOfReplicas: {}
              f:staleReplicaTimeout: {}
              f:storage.kubernetes.io/csiProvisionerIdentity: {}
            f:volumeHandle: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: csi-provisioner
      operation: Update
      time: "2022-03-06T22:52:42Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:42Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"external-attacher/driver-longhorn-io"null: {}
      manager: csi-attacher
      operation: Update
      time: "2022-03-06T22:52:47Z"
    name: pvc-232180f3-6740-4682-ba5c-f4b57a75512b
    resourceVersion: "1001704"
    uid: 56616b3d-15f4-4409-af98-2b8d7d8e0c53
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0
      namespace: cattle-monitoring-system
      resourceVersion: "5433"
      uid: 232180f3-6740-4682-ba5c-f4b57a75512b
    csi:
      driver: driver.longhorn.io
      fsType: ext4
      volumeAttributes:
        baseImage: "null"
        fromBackup: "null"
        migratable: "false"
        numberOfReplicas: "3"
        staleReplicaTimeout: "30"
        storage.kubernetes.io/csiProvisionerIdentity: 1646607139320-8081-driver.longhorn.io
      volumeHandle: pvc-232180f3-6740-4682-ba5c-f4b57a75512b
    persistentVolumeReclaimPolicy: Delete
    storageClassName: longhorn
    volumeMode: Filesystem
  status:
    phase: Bound
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: driver.longhorn.io
    creationTimestamp: "2022-03-06T22:52:38Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2022-03-08T00:02:31Z"
    finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/driver-longhorn-io
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/provisioned-by: {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
          f:csi:
            .: {}
            f:driver: {}
            f:fsType: {}
            f:volumeAttributes:
              .: {}
              f:baseImage: {}
              f:fromBackup: {}
              f:migratable: {}
              f:numberOfReplicas: {}
              f:staleReplicaTimeout: {}
              f:storage.kubernetes.io/csiProvisionerIdentity: {}
            f:volumeHandle: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: csi-provisioner
      operation: Update
      time: "2022-03-06T22:52:38Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:38Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"external-attacher/driver-longhorn-io"null: {}
      manager: csi-attacher
      operation: Update
      time: "2022-03-06T22:52:49Z"
    name: pvc-ce3fa571-6642-4018-b7fd-9eb2c1e56191
    resourceVersion: "1001668"
    uid: 7da70370-ff08-4cef-8e4d-31329b85da73
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Mi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: rancher-monitoring-grafana
      namespace: cattle-monitoring-system
      resourceVersion: "4520"
      uid: ce3fa571-6642-4018-b7fd-9eb2c1e56191
    csi:
      driver: driver.longhorn.io
      fsType: ext4
      volumeAttributes:
        baseImage: "null"
        fromBackup: "null"
        migratable: "false"
        numberOfReplicas: "3"
        staleReplicaTimeout: "30"
        storage.kubernetes.io/csiProvisionerIdentity: 1646607139320-8081-driver.longhorn.io
      volumeHandle: pvc-ce3fa571-6642-4018-b7fd-9eb2c1e56191
    persistentVolumeReclaimPolicy: Delete
    storageClassName: longhorn
    volumeMode: Filesystem
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: "14658865"
