apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: KubeVirt
  metadata:
    annotations:
      kubevirt.io/latest-observed-api-version: v1
      kubevirt.io/storage-observed-api-version: v1alpha3
      meta.helm.sh/release-name: harvester
      meta.helm.sh/release-namespace: harvester-system
      objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
    creationTimestamp: "2022-03-06T22:50:37Z"
    finalizers:
    - foregroundDeleteKubeVirt
    generation: 2
    labels:
      app.kubernetes.io/component: metadata
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kubevirt
      app.kubernetes.io/part-of: kubevirt
      app.kubernetes.io/version: v1
      helm.sh/chart: kubevirt-0.1.0
      helm.sh/release: harvester
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:helm.sh/release: {}
            f:objectset.rio.cattle.io/hash: {}
        f:spec:
          .: {}
          f:configuration:
            .: {}
            f:developerConfiguration:
              .: {}
              f:featureGates: {}
            f:emulatedMachines: {}
            f:network:
              .: {}
              f:defaultNetworkInterface: {}
              f:permitBridgeInterfaceOnPodNetwork: {}
              f:permitSlirpInterface: {}
          f:customizeComponents:
            .: {}
            f:patches: {}
          f:monitorAccount: {}
          f:monitorNamespace: {}
      manager: fleetagent
      operation: Update
      time: "2022-03-06T22:50:37Z"
    - apiVersion: kubevirt.io/v1alpha3
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kubevirt.io/latest-observed-api-version: {}
            f:kubevirt.io/storage-observed-api-version: {}
          f:finalizers:
            .: {}
            v:"foregroundDeleteKubeVirt"null: {}
        f:spec:
          f:certificateRotateStrategy: {}
          f:workloadUpdateStrategy: {}
        f:status:
          .: {}
          f:conditions: {}
          f:generations: {}
          f:observedDeploymentConfig: {}
          f:observedDeploymentID: {}
          f:observedKubeVirtRegistry: {}
          f:observedKubeVirtVersion: {}
          f:operatorVersion: {}
          f:outdatedVirtualMachineInstanceWorkloads: {}
          f:phase: {}
          f:targetDeploymentConfig: {}
          f:targetDeploymentID: {}
          f:targetKubeVirtRegistry: {}
          f:targetKubeVirtVersion: {}
      manager: Go-http-client
      operation: Update
      time: "2022-03-06T22:54:36Z"
    name: kubevirt
    namespace: harvester-system
    resourceVersion: "11716361"
    uid: ab9e6496-8a6f-4152-b458-66f27e5efa4e
  spec:
    certificateRotateStrategy: {}
    configuration:
      developerConfiguration:
        featureGates:
        - LiveMigration
        - HotplugVolumes
      emulatedMachines:
      - q35
      - pc-q35*
      - pc
      - pc-i440fx*
      network:
        defaultNetworkInterface: bridge
        permitBridgeInterfaceOnPodNetwork: true
        permitSlirpInterface: true
    customizeComponents:
      patches:
      - patch: '{"webhooks":[{"name":"kubevirt-validator.kubevirt.io","failurePolicy":"Ignore"},{"name":"kubevirt-update-validator.kubevirt.io","failurePolicy":"Ignore"}]}'
        resourceName: virt-operator-validator
        resourceType: ValidatingWebhookConfiguration
        type: strategic
    monitorAccount: rancher-monitoring-operator
    monitorNamespace: cattle-monitoring-system
    workloadUpdateStrategy: {}
  status:
    conditions:
    - lastProbeTime: "2022-03-08T00:13:28Z"
      lastTransitionTime: "2022-03-08T00:13:28Z"
      message: All components are ready.
      reason: AllComponentsReady
      status: "True"
      type: Available
    - lastProbeTime: "2022-03-08T00:13:28Z"
      lastTransitionTime: "2022-03-08T00:13:28Z"
      message: All components are ready.
      reason: AllComponentsReady
      status: "False"
      type: Progressing
    - lastProbeTime: "2022-03-08T00:13:28Z"
      lastTransitionTime: "2022-03-08T00:13:28Z"
      message: All components are ready.
      reason: AllComponentsReady
      status: "False"
      type: Degraded
    - lastProbeTime: "2022-03-06T22:54:31Z"
      lastTransitionTime: "null"
      message: All resources were created.
      reason: AllResourcesCreated
      status: "True"
      type: Created
    generations:
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineinstances.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineinstancepresets.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineinstancereplicasets.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachines.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineinstancemigrations.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachinesnapshots.snapshot.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachinesnapshotcontents.snapshot.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachinerestores.snapshot.kubevirt.io
      resource: customresourcedefinitions
    - group: admissionregistration.k8s.io
      lastGeneration: 5
      name: virt-operator-validator
      resource: validatingwebhookconfigurations
    - group: admissionregistration.k8s.io
      lastGeneration: 5
      name: virt-api-validator
      resource: validatingwebhookconfigurations
    - group: admissionregistration.k8s.io
      lastGeneration: 5
      name: virt-api-mutator
      resource: mutatingwebhookconfigurations
    - group: apps
      lastGeneration: 1
      name: virt-api
      namespace: harvester-system
      resource: deployments
    - group: apps
      lastGeneration: 1
      name: virt-api-pdb
      namespace: harvester-system
      resource: poddisruptionbudgets
    - group: apps
      lastGeneration: 1
      name: virt-controller
      namespace: harvester-system
      resource: deployments
    - group: apps
      lastGeneration: 1
      name: virt-controller-pdb
      namespace: harvester-system
      resource: poddisruptionbudgets
    - group: apps
      lastGeneration: 1
      name: virt-handler
      namespace: harvester-system
      resource: daemonsets
    observedDeploymentConfig: '{"id":"d3df7f87ee723ed71ca49f6c5cab7566dd4dc500","namespace":"harvester-system","registry":"registry.suse.com/suse/sles/15.3","kubeVirtVersion":"0.45.0-8.4.3","additionalProperties":{"CertificateRotationStrategy":"\u003cv1.KubeVirtCertificateRotateStrategy
      Value\u003e","Configuration":"\u003cv1.KubeVirtConfiguration Value\u003e","CustomizeComponents":"\u003cv1.CustomizeComponents
      Value\u003e","ImagePullPolicy":"","Infra":"\u003c*v1.ComponentConfig Value\u003e","MonitorAccount":"rancher-monitoring-operator","MonitorNamespace":"cattle-monitoring-system","ProductName":"","ProductVersion":"","UninstallStrategy":"","WorkloadUpdateStrategy":"\u003cv1.KubeVirtWorkloadUpdateStrategy
      Value\u003e","Workloads":"\u003c*v1.ComponentConfig Value\u003e"}}'
    observedDeploymentID: d3df7f87ee723ed71ca49f6c5cab7566dd4dc500
    observedKubeVirtRegistry: registry.suse.com/suse/sles/15.3
    observedKubeVirtVersion: 0.45.0-8.4.3
    operatorVersion: v0.45.0
    outdatedVirtualMachineInstanceWorkloads: 0
    phase: Deployed
    targetDeploymentConfig: '{"id":"d3df7f87ee723ed71ca49f6c5cab7566dd4dc500","namespace":"harvester-system","registry":"registry.suse.com/suse/sles/15.3","kubeVirtVersion":"0.45.0-8.4.3","additionalProperties":{"CertificateRotationStrategy":"\u003cv1.KubeVirtCertificateRotateStrategy
      Value\u003e","Configuration":"\u003cv1.KubeVirtConfiguration Value\u003e","CustomizeComponents":"\u003cv1.CustomizeComponents
      Value\u003e","ImagePullPolicy":"","Infra":"\u003c*v1.ComponentConfig Value\u003e","MonitorAccount":"rancher-monitoring-operator","MonitorNamespace":"cattle-monitoring-system","ProductName":"","ProductVersion":"","UninstallStrategy":"","WorkloadUpdateStrategy":"\u003cv1.KubeVirtWorkloadUpdateStrategy
      Value\u003e","Workloads":"\u003c*v1.ComponentConfig Value\u003e"}}'
    targetDeploymentID: d3df7f87ee723ed71ca49f6c5cab7566dd4dc500
    targetKubeVirtRegistry: registry.suse.com/suse/sles/15.3
    targetKubeVirtVersion: 0.45.0-8.4.3
kind: List
metadata:
  continue: "null"
  resourceVersion: "14659189"
