apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:53:26Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:57Z"
    name: ingress-expose
    namespace: kube-system
    resourceVersion: "1026229"
    uid: 3810b01f-c1d1-48d0-9afd-46732b418130
  subsets:
  - addresses:
    - ip: 172.16.132.182
      nodeName: node1
      targetRef:
        kind: Pod
        name: rke2-ingress-nginx-controller-vx265
        namespace: kube-system
        resourceVersion: "3885"
        uid: 0dc50432-c2dd-42e2-b633-3df1e5b055be
    ports:
    - name: https-internal
      port: 443
      protocol: TCP
    - name: http
      port: 80
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"kube-vip-cloud-provider-0_2d3a4ad0-5a39-4949-aaf4-62460d97f724","leaseDurationSeconds":15,"acquireTime":"2022-03-06T22:51:36Z","renewTime":"2022-03-22T23:49:41Z","leaderTransitions":0}'
    creationTimestamp: "2022-03-06T22:51:36Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:control-plane.alpha.kubernetes.io/leader: {}
      manager: kube-vip-cloud-provider
      operation: Update
      time: "2022-03-06T22:51:36Z"
    name: kube-vip-cloud-controller
    namespace: kube-system
    resourceVersion: "14658969"
    uid: 6848ef8d-167c-42d5-8172-ef5569303920
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:52:04Z"
    labels:
      app: rancher-monitoring-coredns
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: rancher-monitoring
      app.kubernetes.io/version: 100.1.0_up19.0.3
      chart: rancher-monitoring-100.1.0_up19.0.3
      heritage: Helm
      jobLabel: coredns
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
      release: rancher-monitoring
      service.kubernetes.io/headless: "null"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:chart: {}
            f:heritage: {}
            f:jobLabel: {}
            f:objectset.rio.cattle.io/hash: {}
            f:release: {}
            f:service.kubernetes.io/headless: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:07Z"
    name: rancher-monitoring-coredns
    namespace: kube-system
    resourceVersion: "1025100"
    uid: 1c9d44d4-f9fd-4f65-933f-29903a1b4c18
  subsets:
  - addresses:
    - ip: 10.52.0.2
      nodeName: node1
      targetRef:
        kind: Pod
        name: rke2-coredns-rke2-coredns-5679c85bbb-ph7cc
        namespace: kube-system
        resourceVersion: "3851"
        uid: e2cf7633-acef-4515-ae54-07aa9eb5d0a9
    ports:
    - name: http-metrics
      port: 9153
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:52:30Z"
    labels:
      app.kubernetes.io/managed-by: prometheus-operator
      app.kubernetes.io/name: kubelet
      k8s-app: kubelet
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:k8s-app: {}
        f:subsets: {}
      manager: operator
      operation: Update
      time: "2022-03-06T22:52:30Z"
    name: rancher-monitoring-kubelet
    namespace: kube-system
    resourceVersion: "1027286"
    uid: fc934bd2-c4f1-498d-95bd-9bc7506f7a40
  subsets:
  - addresses:
    - ip: 172.16.132.182
      targetRef:
        kind: Node
        name: node1
        uid: c4cd362a-7999-46e3-8744-b65c1581fd4e
    ports:
    - name: https-metrics
      port: 10250
      protocol: TCP
    - name: http-metrics
      port: 10255
      protocol: TCP
    - name: cadvisor
      port: 4194
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:47:19Z"
    labels:
      app.kubernetes.io/instance: rke2-coredns
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rke2-coredns
      helm.sh/chart: rke2-coredns-1.16.401-build2021111901
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: CoreDNS
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
            f:k8s-app: {}
            f:kubernetes.io/cluster-service: {}
            f:kubernetes.io/name: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:07Z"
    name: rke2-coredns-rke2-coredns
    namespace: kube-system
    resourceVersion: "1025099"
    uid: 5d0c4007-2353-4042-a59f-a8d365d7632d
  subsets:
  - addresses:
    - ip: 10.52.0.2
      nodeName: node1
      targetRef:
        kind: Pod
        name: rke2-coredns-rke2-coredns-5679c85bbb-ph7cc
        namespace: kube-system
        resourceVersion: "3851"
        uid: e2cf7633-acef-4515-ae54-07aa9eb5d0a9
    ports:
    - name: tcp-53
      port: 53
      protocol: TCP
    - name: udp-53
      port: 53
      protocol: UDP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:48:04Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: rke2-ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rke2-ingress-nginx
      app.kubernetes.io/version: 1.0.2
      helm.sh/chart: rke2-ingress-nginx-4.0.306
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:57Z"
    name: rke2-ingress-nginx-controller-admission
    namespace: kube-system
    resourceVersion: "1026225"
    uid: 031d99a1-9aba-4708-b202-5403dbf2ab4b
  subsets:
  - addresses:
    - ip: 172.16.132.182
      nodeName: node1
      targetRef:
        kind: Pod
        name: rke2-ingress-nginx-controller-vx265
        namespace: kube-system
        resourceVersion: "3885"
        uid: 0dc50432-c2dd-42e2-b633-3df1e5b055be
    ports:
    - appProtocol: https
      name: https-webhook
      port: 8444
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:47:58Z"
    creationTimestamp: "2022-03-06T22:47:58Z"
    labels:
      app: rke2-metrics-server
      app.kubernetes.io/managed-by: Helm
      chart: rke2-metrics-server-2.11.100-build2021111904
      heritage: Helm
      release: rke2-metrics-server
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:chart: {}
            f:heritage: {}
            f:release: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:48:03Z"
    name: rke2-metrics-server
    namespace: kube-system
    resourceVersion: "4186"
    uid: 12653e04-360c-492e-ab88-13868afb80ae
  subsets:
  - addresses:
    - ip: 10.52.0.7
      nodeName: node1
      targetRef:
        kind: Pod
        name: rke2-metrics-server-8574659c85-s467p
        namespace: kube-system
        resourceVersion: "3861"
        uid: ce5f8fcc-bd30-43a6-bba6-448cc8c09434
    ports:
    - port: 8443
      protocol: TCP
kind: List
metadata:
  resourceVersion: "14658989"
