apiVersion: v1
items:
- apiVersion: v1
  data:
    cloudInit: |-
      package_update: false
      packages:
        - qemu-guest-agent
      runcmd:
        - - systemctl
          - enable
          - '--now'
          - qemu-guest-agent
        - - systemctl
          - start
          - '--no-block'
          - qemu-guest-agent
      users:
        - default
        - name: demo
          shell: /bin/bash
          groups: users
          lock_passwd: false
          passwd: $1$SaltSalt$l9QBhniZhOX6v9cL.Hh4x/
          sudo: ALL=(ALL) NOPASSWD:ALL
  kind: ConfigMap
  metadata:
    creationTimestamp: "2022-03-06T23:11:03Z"
    labels:
      harvesterhci.io/cloud-init-template: user
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:cloudInit: {}
        f:metadata:
          f:labels:
            .: {}
            f:harvesterhci.io/cloud-init-template: {}
      manager: harvester
      operation: Update
      time: "2022-03-06T23:11:03Z"
    name: demouser
    namespace: default
    resourceVersion: "18013"
    uid: 89fa5e31-caf9-476b-93f3-c90e689ba7a5
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBejCCAR+gAwIBAgIBADAKBggqhkjOPQQDAjAkMSIwIAYDVQQDDBlya2UyLXNl
      cnZlci1jYUAxNjQ2NjA2NzYxMB4XDTIyMDMwNjIyNDYwMVoXDTMyMDMwMzIyNDYw
      MVowJDEiMCAGA1UEAwwZcmtlMi1zZXJ2ZXItY2FAMTY0NjYwNjc2MTBZMBMGByqG
      SM49AgEGCCqGSM49AwEHA0IABH+0BOq7FJij86zAjeedEnaJ+TkxCjFNcDBoo/R5
      XIuYHfO3cCeVIuvO6X//Rep7MG+bcbTenCP4RhwDHYKD+J2jQjBAMA4GA1UdDwEB
      /wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRBQ79Om8U8JEONqyG+
      21eN8KmH1DAKBggqhkjOPQQDAgNJADBGAiEAsNa9lXUL4SA4WC6P4v6yDCTILlZA
      yB4jTWBnW24PB/gCIQCv7238+JiviH9sFUWdFE2zxZ3AGLyPkwCcj/7ZppcWRA==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    creationTimestamp: "2022-03-06T22:47:10Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:47:10Z"
    name: kube-root-ca.crt
    namespace: default
    resourceVersion: "575"
    uid: a33d2f20-a2dc-4a7e-bfe5-0b296df798bc
kind: List
metadata:
  resourceVersion: "14658968"
