apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2022-03-06T22:47:09Z"
    name: default
    namespace: default
    resourceVersion: "555"
    uid: 136cbb29-899d-4a1a-b4d4-ca7288a8e2ae
  secrets:
  - name: default-token-j9gnp
kind: List
metadata:
  resourceVersion: "14658971"
