apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.68
    conditions:
      ready: true
    hostname: prometheus-rancher-monitoring-prometheus-0
    nodeName: node1
    targetRef:
      kind: Pod
      name: prometheus-rancher-monitoring-prometheus-0
      namespace: cattle-monitoring-system
      resourceVersion: "6522"
      uid: 49528edb-4c3d-481e-9f44-520fda36020d
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:53:35Z"
    creationTimestamp: "2022-03-06T22:52:38Z"
    generateName: prometheus-operated-
    generation: 3
    labels:
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: prometheus-operated
      operated-prometheus: "true"
      service.kubernetes.io/headless: "null"
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:kubernetes.io/service-name: {}
            f:operated-prometheus: {}
            f:service.kubernetes.io/headless: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"7c0dcda4-428d-4cd2-97b3-cd4016ef55bb"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:53:15Z"
    name: prometheus-operated-txrwp
    namespace: cattle-monitoring-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: prometheus-operated
      uid: 7c0dcda4-428d-4cd2-97b3-cd4016ef55bb
    resourceVersion: "6526"
    uid: bd390c35-02b0-4e18-98e6-bad25dd8a8c3
  ports:
  - name: nginx-http
    port: 9090
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.69
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: rancher-monitoring-grafana-d9c56d79b-rt4pt
      namespace: cattle-monitoring-system
      resourceVersion: "6711"
      uid: e199d5a7-36fd-4c06-ad81-de3ab0ce98cc
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:53:49Z"
    creationTimestamp: "2022-03-06T22:52:03Z"
    generateName: rancher-monitoring-grafana-
    generation: 3
    labels:
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 7.5.11
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: grafana-6.16.14
      kubernetes.io/service-name: rancher-monitoring-grafana
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:helm.sh/chart: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"a2760f6a-61a9-4eaa-9754-f706b6e98af4"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:53:11Z"
    name: rancher-monitoring-grafana-7sz8v
    namespace: cattle-monitoring-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: rancher-monitoring-grafana
      uid: a2760f6a-61a9-4eaa-9754-f706b6e98af4
    resourceVersion: "6716"
    uid: 249f9e43-f822-4449-bc7c-2d6aa80aa219
  ports:
  - name: nginx-http
    port: 8080
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.58
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: rancher-monitoring-kube-state-metrics-5bc8bb48bd-dbk5t
      namespace: cattle-monitoring-system
      resourceVersion: "5211"
      uid: 1fbcdfb6-ca64-4285-9dc1-fa9db9e26fc2
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:25Z"
    creationTimestamp: "2022-03-06T22:52:03Z"
    generateName: rancher-monitoring-kube-state-metrics-
    generation: 3
    labels:
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-state-metrics
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: kube-state-metrics-3.5.2
      kubernetes.io/service-name: rancher-monitoring-kube-state-metrics
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:helm.sh/chart: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4afa36ce-caf0-4932-a8f5-229d472cddef"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:23Z"
    name: rancher-monitoring-kube-state-metrics-vl4hz
    namespace: cattle-monitoring-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: rancher-monitoring-kube-state-metrics
      uid: 4afa36ce-caf0-4932-a8f5-229d472cddef
    resourceVersion: "5214"
    uid: 376f5025-208d-4c57-8d02-27bda32bb27f
  ports:
  - name: http
    port: 8080
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.59
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: rancher-monitoring-operator-559767d69b-trm9m
      namespace: cattle-monitoring-system
      resourceVersion: "5193"
      uid: 9313eaf0-885a-49ea-8b1f-6809fef614ae
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:22Z"
    creationTimestamp: "2022-03-06T22:52:04Z"
    generateName: rancher-monitoring-operator-
    generation: 2
    labels:
      app: rancher-monitoring-operator
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: rancher-monitoring
      app.kubernetes.io/version: 100.1.0_up19.0.3
      chart: rancher-monitoring-100.1.0_up19.0.3
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      heritage: Helm
      kubernetes.io/service-name: rancher-monitoring-operator
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
      release: rancher-monitoring
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:chart: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:heritage: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
            f:release: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"162c38e4-fcc9-4fa0-9c0c-16e0140544dd"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:24Z"
    name: rancher-monitoring-operator-d4tmg
    namespace: cattle-monitoring-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: rancher-monitoring-operator
      uid: 162c38e4-fcc9-4fa0-9c0c-16e0140544dd
    resourceVersion: "5196"
    uid: e1659eac-1797-4019-a4ac-f5d2253b71c9
  ports:
  - name: https
    port: 8443
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.60
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: rancher-monitoring-prometheus-adapter-8846d4757-glskx
      namespace: cattle-monitoring-system
      resourceVersion: "5839"
      uid: 1f006475-0769-4c01-bfb6-b19331247aba
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:55Z"
    creationTimestamp: "2022-03-06T22:52:03Z"
    generateName: rancher-monitoring-prometheus-adapter-
    generation: 3
    labels:
      app: prometheus-adapter
      app.kubernetes.io/managed-by: Helm
      chart: prometheus-adapter-2.17.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      heritage: Helm
      kubernetes.io/service-name: rancher-monitoring-prometheus-adapter
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
      release: rancher-monitoring
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:chart: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:heritage: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
            f:release: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"0e9fd8c1-3c55-4d72-b5a2-0e80615f4e10"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:25Z"
    name: rancher-monitoring-prometheus-adapter-ns5x6
    namespace: cattle-monitoring-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: rancher-monitoring-prometheus-adapter
      uid: 0e9fd8c1-3c55-4d72-b5a2-0e80615f4e10
    resourceVersion: "5841"
    uid: 3b1d3d47-0785-4127-ae00-6d827a9889e4
  ports:
  - name: "null"
    port: 6443
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.68
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: prometheus-rancher-monitoring-prometheus-0
      namespace: cattle-monitoring-system
      resourceVersion: "6522"
      uid: 49528edb-4c3d-481e-9f44-520fda36020d
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:53:35Z"
    creationTimestamp: "2022-03-06T22:52:04Z"
    generateName: rancher-monitoring-prometheus-
    generation: 3
    labels:
      app: rancher-monitoring-prometheus
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: rancher-monitoring
      app.kubernetes.io/version: 100.1.0_up19.0.3
      chart: rancher-monitoring-100.1.0_up19.0.3
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      heritage: Helm
      kubernetes.io/service-name: rancher-monitoring-prometheus
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
      release: rancher-monitoring
      self-monitor: "true"
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:chart: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:heritage: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
            f:release: {}
            f:self-monitor: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"30f887ec-3b2e-4b99-9b0e-f6d063ef3645"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:53:15Z"
    name: rancher-monitoring-prometheus-kbnl9
    namespace: cattle-monitoring-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: rancher-monitoring-prometheus
      uid: 30f887ec-3b2e-4b99-9b0e-f6d063ef3645
    resourceVersion: "6524"
    uid: 62bcf4c9-78c2-46ee-8e95-3abc88202bd3
  ports:
  - name: nginx-http
    port: 8081
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 172.16.132.182
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: rancher-monitoring-prometheus-node-exporter-dsvgt
      namespace: cattle-monitoring-system
      resourceVersion: "5084"
      uid: 5af16d38-9a06-47d4-af7f-9cb3cdf4eca7
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2022-03-06T22:52:04Z"
    generateName: rancher-monitoring-prometheus-node-exporter-
    generation: 10
    labels:
      app: prometheus-node-exporter
      app.kubernetes.io/managed-by: Helm
      chart: prometheus-node-exporter-2.2.0
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      heritage: Helm
      jobLabel: node-exporter
      kubernetes.io/service-name: rancher-monitoring-prometheus-node-exporter
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
      release: rancher-monitoring
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:chart: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:heritage: {}
            f:jobLabel: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
            f:release: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4155ab99-4ace-432a-9761-72a5dd1df855"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:57Z"
    name: rancher-monitoring-prometheus-node-exporter-vqzqm
    namespace: cattle-monitoring-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: rancher-monitoring-prometheus-node-exporter
      uid: 4155ab99-4ace-432a-9761-72a5dd1df855
    resourceVersion: "1026243"
    uid: 98716415-76e2-498c-9800-5152256f69bd
  ports:
  - name: metrics
    port: 9796
    protocol: TCP
kind: List
metadata:
  resourceVersion: "14659119"
