apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBejCCAR+gAwIBAgIBADAKBggqhkjOPQQDAjAkMSIwIAYDVQQDDBlya2UyLXNl
      cnZlci1jYUAxNjQ2NjA2NzYxMB4XDTIyMDMwNjIyNDYwMVoXDTMyMDMwMzIyNDYw
      MVowJDEiMCAGA1UEAwwZcmtlMi1zZXJ2ZXItY2FAMTY0NjYwNjc2MTBZMBMGByqG
      SM49AgEGCCqGSM49AwEHA0IABH+0BOq7FJij86zAjeedEnaJ+TkxCjFNcDBoo/R5
      XIuYHfO3cCeVIuvO6X//Rep7MG+bcbTenCP4RhwDHYKD+J2jQjBAMA4GA1UdDwEB
      /wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRBQ79Om8U8JEONqyG+
      21eN8KmH1DAKBggqhkjOPQQDAgNJADBGAiEAsNa9lXUL4SA4WC6P4v6yDCTILlZA
      yB4jTWBnW24PB/gCIQCv7238+JiviH9sFUWdFE2zxZ3AGLyPkwCcj/7ZppcWRA==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    creationTimestamp: "2022-03-06T22:50:36Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:50:36Z"
    name: kube-root-ca.crt
    namespace: longhorn-system
    resourceVersion: "3046"
    uid: 82c4730f-ead2-4b85-88fc-9592c84cfac6
- apiVersion: v1
  data:
    default-setting.yaml: "backup-target: \nbackup-target-credential-secret: \nallow-recurring-job-while-volume-detached:
      \ncreate-default-disk-labeled-nodes: \ndefault-data-path: /var/lib/harvester/defaultdisk\nreplica-soft-anti-affinity:
      \nreplica-auto-balance: \nstorage-over-provisioning-percentage: \nstorage-minimal-available-percentage:
      \nupgrade-checker: \ndefault-replica-count: \ndefault-data-locality: \ndefault-longhorn-static-storage-class:
      \nbackupstore-poll-interval: \ntaint-toleration: kubevirt.io/drain:NoSchedule\nsystem-managed-components-node-selector:
      \npriority-class: \nauto-salvage: \nauto-delete-pod-when-volume-detached-unexpectedly:
      \ndisable-scheduling-on-cordoned-node: \nreplica-zone-soft-anti-affinity: \nnode-down-pod-deletion-policy:
      \nallow-node-drain-with-last-healthy-replica: \nmkfs-ext4-parameters: \ndisable-replica-rebuild:
      \nreplica-replenishment-wait-interval: \nconcurrent-replica-rebuild-per-node-limit:
      \ndisable-revision-counter: \nsystem-managed-pods-image-pull-policy: \nallow-volume-creation-with-degraded-availability:
      \nauto-cleanup-system-generated-snapshot: \nconcurrent-automatic-engine-upgrade-per-node-limit:
      3\nbacking-image-cleanup-wait-interval: \nbacking-image-recovery-wait-interval:
      \nguaranteed-engine-manager-cpu: \nguaranteed-replica-manager-cpu:"
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: harvester
      meta.helm.sh/release-namespace: harvester-system
      objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
    creationTimestamp: "2022-03-06T22:50:36Z"
    labels:
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.2.3
      helm.sh/chart: longhorn-1.2.3
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:default-setting.yaml: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:objectset.rio.cattle.io/hash: {}
      manager: fleetagent
      operation: Update
      time: "2022-03-06T22:50:36Z"
    name: longhorn-default-setting
    namespace: longhorn-system
    resourceVersion: "3060"
    uid: 9501dbb3-fb90-4e85-9773-6b17cd3b6dfd
- apiVersion: v1
  data:
    storageclass.yaml: |
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: longhorn
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      parameters:
        numberOfReplicas: "3"
        staleReplicaTimeout: "30"
        fromBackup: ""
        baseImage: ""
        migratable: "true"
  kind: ConfigMap
  metadata:
    annotations:
      helm.sh/hook: post-install,post-upgrade
    creationTimestamp: "2022-03-22T18:54:56Z"
    labels:
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: harvester
      app.kubernetes.io/version: 0.1.x
      helm.sh/chart: harvester-0.0.0-dev
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:storageclass.yaml: {}
        f:metadata:
          f:annotations:
            .: {}
            f:helm.sh/hook: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
      manager: fleetagent
      operation: Update
      time: "2022-03-22T18:54:56Z"
    name: longhorn-storageclass
    namespace: longhorn-system
    resourceVersion: "14472688"
    uid: e2881906-ecf4-49b7-a7a3-eb1f99bd1c1c
kind: List
metadata:
  resourceVersion: "14659212"
