apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:17Z"
    creationTimestamp: "2022-03-06T22:51:59Z"
    labels:
      app: csi-attacher
      longhorn.io/managed-by: longhorn-manager
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:longhorn.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:16Z"
    name: csi-attacher
    namespace: longhorn-system
    resourceVersion: "5059"
    uid: 6022fbce-b15b-4675-995a-5f8ba0ed4f79
  subsets:
  - addresses:
    - ip: 10.52.0.45
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-attacher-66fcbbff5c-qjcrr
        namespace: longhorn-system
        resourceVersion: "4959"
        uid: 4767a499-f28f-4c18-a116-67328a8b3859
    - ip: 10.52.0.46
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-attacher-66fcbbff5c-drjmf
        namespace: longhorn-system
        resourceVersion: "4982"
        uid: 59a97092-6b6f-412a-ae85-6ca3fd0b874e
    - ip: 10.52.0.47
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-attacher-66fcbbff5c-h72z5
        namespace: longhorn-system
        resourceVersion: "5054"
        uid: 9f9f45fe-4ce8-418a-ab9d-c9df5524fc73
    ports:
    - name: dummy
      port: 12345
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:17Z"
    creationTimestamp: "2022-03-06T22:51:59Z"
    labels:
      app: csi-provisioner
      longhorn.io/managed-by: longhorn-manager
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:longhorn.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:16Z"
    name: csi-provisioner
    namespace: longhorn-system
    resourceVersion: "4998"
    uid: ae0b3d8e-bb99-41a0-b91b-cd3ef099a27c
  subsets:
  - addresses:
    - ip: 10.52.0.48
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-provisioner-84fcfbf785-tqz2w
        namespace: longhorn-system
        resourceVersion: "4996"
        uid: c0020ac1-b676-4362-beca-0d00024e28e3
    - ip: 10.52.0.49
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-provisioner-84fcfbf785-d5pbx
        namespace: longhorn-system
        resourceVersion: "4965"
        uid: e8703585-4cef-4e04-bbcf-a6d32a2b0399
    - ip: 10.52.0.50
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-provisioner-84fcfbf785-q4clc
        namespace: longhorn-system
        resourceVersion: "4972"
        uid: 96b2e49e-d29a-4f7b-864d-36973907976e
    ports:
    - name: dummy
      port: 12345
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:17Z"
    creationTimestamp: "2022-03-06T22:52:00Z"
    labels:
      app: csi-resizer
      longhorn.io/managed-by: longhorn-manager
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:longhorn.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:16Z"
    name: csi-resizer
    namespace: longhorn-system
    resourceVersion: "5027"
    uid: 94f8f715-3b8b-4e85-ae27-6197074b1741
  subsets:
  - addresses:
    - ip: 10.52.0.51
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-resizer-558f9d8df-69txc
        namespace: longhorn-system
        resourceVersion: "4950"
        uid: fb270a41-fc99-4867-a8e8-91484db04015
    - ip: 10.52.0.52
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-resizer-558f9d8df-8swq7
        namespace: longhorn-system
        resourceVersion: "5015"
        uid: c55d3ca4-9369-4b09-9439-2e6c195dc605
    - ip: 10.52.0.61
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-resizer-558f9d8df-mz4x6
        namespace: longhorn-system
        resourceVersion: "5025"
        uid: 5d0f47f7-3246-48d5-b4bd-4b02544d2088
    ports:
    - name: dummy
      port: 12345
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:17Z"
    creationTimestamp: "2022-03-06T22:52:00Z"
    labels:
      app: csi-snapshotter
      longhorn.io/managed-by: longhorn-manager
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:longhorn.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:17Z"
    name: csi-snapshotter
    namespace: longhorn-system
    resourceVersion: "5040"
    uid: 98bb11ba-6fad-454f-a524-2e47a07a6257
  subsets:
  - addresses:
    - ip: 10.52.0.53
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-snapshotter-7dc99d7f87-sr54m
        namespace: longhorn-system
        resourceVersion: "4976"
        uid: cfaa5c14-75be-4a72-bd54-90f673ed5b07
    - ip: 10.52.0.55
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-snapshotter-7dc99d7f87-ggbk7
        namespace: longhorn-system
        resourceVersion: "5005"
        uid: f3d7ce6b-6680-42ed-9af8-e00773d1a823
    - ip: 10.52.0.56
      nodeName: node1
      targetRef:
        kind: Pod
        name: csi-snapshotter-7dc99d7f87-5tbwz
        namespace: longhorn-system
        resourceVersion: "5039"
        uid: 30de0c27-5c72-45b3-a359-2bdb44c1c0de
    ports:
    - name: dummy
      port: 12345
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:50:37Z"
    labels:
      app: longhorn-manager
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.2.3
      helm.sh/chart: longhorn-1.2.3
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:objectset.rio.cattle.io/hash: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:57Z"
    name: longhorn-backend
    namespace: longhorn-system
    resourceVersion: "1026238"
    uid: 822b4dad-30f1-4c64-9c2f-e8204e6d448e
  subsets:
  - addresses:
    - ip: 10.52.0.35
      nodeName: node1
      targetRef:
        kind: Pod
        name: longhorn-manager-pmjr9
        namespace: longhorn-system
        resourceVersion: "4246"
        uid: ef02266a-18d5-48c8-9c15-959cfe6a95f5
    ports:
    - name: manager
      port: 9500
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:50:37Z"
    labels:
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.2.3
      helm.sh/chart: longhorn-1.2.3
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
      service.kubernetes.io/headless: "null"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:objectset.rio.cattle.io/hash: {}
            f:service.kubernetes.io/headless: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:07Z"
    name: longhorn-engine-manager
    namespace: longhorn-system
    resourceVersion: "1025122"
    uid: 98dc8dd9-3e2a-4b8b-8a62-fd0dc6573dd5
  subsets:
  - addresses:
    - ip: 10.52.0.43
      nodeName: node1
      targetRef:
        kind: Pod
        name: instance-manager-e-5708ef52
        namespace: longhorn-system
        resourceVersion: "5141"
        uid: 27b74445-4bfe-4db5-aa4a-0266bf411604
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:50:37Z"
    creationTimestamp: "2022-03-06T22:50:37Z"
    labels:
      app: longhorn-ui
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.2.3
      helm.sh/chart: longhorn-1.2.3
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:objectset.rio.cattle.io/hash: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:51:51Z"
    name: longhorn-frontend
    namespace: longhorn-system
    resourceVersion: "4187"
    uid: f9a8c5a4-c6f5-4219-b7f6-5f82ab696c84
  subsets:
  - addresses:
    - ip: 10.52.0.40
      nodeName: node1
      targetRef:
        kind: Pod
        name: longhorn-ui-8466bcb8b7-rm9v9
        namespace: longhorn-system
        resourceVersion: "3969"
        uid: ba97cbb8-08ea-4bdc-8422-fec544aeb7d0
    ports:
    - name: http
      port: 8000
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:50:37Z"
    labels:
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.2.3
      helm.sh/chart: longhorn-1.2.3
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
      service.kubernetes.io/headless: "null"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:objectset.rio.cattle.io/hash: {}
            f:service.kubernetes.io/headless: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:07Z"
    name: longhorn-replica-manager
    namespace: longhorn-system
    resourceVersion: "1025115"
    uid: ca773c8f-4a34-4f22-b19a-a13ee002fade
  subsets:
  - addresses:
    - ip: 10.52.0.44
      nodeName: node1
      targetRef:
        kind: Pod
        name: instance-manager-r-9d910deb
        namespace: longhorn-system
        resourceVersion: "5156"
        uid: 69b97f18-f852-404c-9528-818029f3fa08
kind: List
metadata:
  resourceVersion: "14659211"
