apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2022-03-06T22:50:36Z"
    name: default
    namespace: longhorn-system
    resourceVersion: "3104"
    uid: b2b260ca-9581-4d22-a71e-50aaec01b6b3
  secrets:
  - name: default-token-7kcjt
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: harvester
      meta.helm.sh/release-namespace: harvester-system
      objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
    creationTimestamp: "2022-03-06T22:50:36Z"
    labels:
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.2.3
      helm.sh/chart: longhorn-1.2.3
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:objectset.rio.cattle.io/hash: {}
      manager: fleetagent
      operation: Update
      time: "2022-03-06T22:50:36Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:secrets:
          .: {}
          k:{"name":"longhorn-service-account-token-lplgn"}:
            .: {}
            f:name: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:50:36Z"
    name: longhorn-service-account
    namespace: longhorn-system
    resourceVersion: "3068"
    uid: ff51636b-f5da-4320-9d4d-f8453f570417
  secrets:
  - name: longhorn-service-account-token-lplgn
kind: List
metadata:
  resourceVersion: "14659211"
