apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:53:35Z"
    creationTimestamp: "2022-03-06T22:52:38Z"
    labels:
      operated-prometheus: "true"
      service.kubernetes.io/headless: "null"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:operated-prometheus: {}
            f:service.kubernetes.io/headless: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:53:15Z"
    name: prometheus-operated
    namespace: cattle-monitoring-system
    resourceVersion: "6525"
    uid: 2102cdfc-7dc2-449b-b361-59300b883d4d
  subsets:
  - addresses:
    - hostname: prometheus-rancher-monitoring-prometheus-0
      ip: 10.52.0.68
      nodeName: node1
      targetRef:
        kind: Pod
        name: prometheus-rancher-monitoring-prometheus-0
        namespace: cattle-monitoring-system
        resourceVersion: "6522"
        uid: 49528edb-4c3d-481e-9f44-520fda36020d
    ports:
    - name: nginx-http
      port: 9090
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:53:49Z"
    creationTimestamp: "2022-03-06T22:52:03Z"
    labels:
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 7.5.11
      helm.sh/chart: grafana-6.16.14
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:objectset.rio.cattle.io/hash: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:53:11Z"
    name: rancher-monitoring-grafana
    namespace: cattle-monitoring-system
    resourceVersion: "6713"
    uid: 58c69813-da07-45be-aab2-b0c46ada3750
  subsets:
  - addresses:
    - ip: 10.52.0.69
      nodeName: node1
      targetRef:
        kind: Pod
        name: rancher-monitoring-grafana-d9c56d79b-rt4pt
        namespace: cattle-monitoring-system
        resourceVersion: "6711"
        uid: e199d5a7-36fd-4c06-ad81-de3ab0ce98cc
    ports:
    - name: nginx-http
      port: 8080
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:25Z"
    creationTimestamp: "2022-03-06T22:52:03Z"
    labels:
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-state-metrics
      helm.sh/chart: kube-state-metrics-3.5.2
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:helm.sh/chart: {}
            f:objectset.rio.cattle.io/hash: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:23Z"
    name: rancher-monitoring-kube-state-metrics
    namespace: cattle-monitoring-system
    resourceVersion: "5212"
    uid: 4141933f-150f-4b00-bc03-7b7ac1e1c44b
  subsets:
  - addresses:
    - ip: 10.52.0.58
      nodeName: node1
      targetRef:
        kind: Pod
        name: rancher-monitoring-kube-state-metrics-5bc8bb48bd-dbk5t
        namespace: cattle-monitoring-system
        resourceVersion: "5211"
        uid: 1fbcdfb6-ca64-4285-9dc1-fa9db9e26fc2
    ports:
    - name: http
      port: 8080
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:22Z"
    creationTimestamp: "2022-03-06T22:52:04Z"
    labels:
      app: rancher-monitoring-operator
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: rancher-monitoring
      app.kubernetes.io/version: 100.1.0_up19.0.3
      chart: rancher-monitoring-100.1.0_up19.0.3
      heritage: Helm
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
      release: rancher-monitoring
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:chart: {}
            f:heritage: {}
            f:objectset.rio.cattle.io/hash: {}
            f:release: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:24Z"
    name: rancher-monitoring-operator
    namespace: cattle-monitoring-system
    resourceVersion: "5197"
    uid: 7db80daa-31b4-4b70-ac03-59dc4aa27b20
  subsets:
  - addresses:
    - ip: 10.52.0.59
      nodeName: node1
      targetRef:
        kind: Pod
        name: rancher-monitoring-operator-559767d69b-trm9m
        namespace: cattle-monitoring-system
        resourceVersion: "5193"
        uid: 9313eaf0-885a-49ea-8b1f-6809fef614ae
    ports:
    - name: https
      port: 8443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:53:35Z"
    creationTimestamp: "2022-03-06T22:52:04Z"
    labels:
      app: rancher-monitoring-prometheus
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: rancher-monitoring
      app.kubernetes.io/version: 100.1.0_up19.0.3
      chart: rancher-monitoring-100.1.0_up19.0.3
      heritage: Helm
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
      release: rancher-monitoring
      self-monitor: "true"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:chart: {}
            f:heritage: {}
            f:objectset.rio.cattle.io/hash: {}
            f:release: {}
            f:self-monitor: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:53:15Z"
    name: rancher-monitoring-prometheus
    namespace: cattle-monitoring-system
    resourceVersion: "6523"
    uid: c5d12658-80f9-4953-aabe-3e1267cf57c9
  subsets:
  - addresses:
    - ip: 10.52.0.68
      nodeName: node1
      targetRef:
        kind: Pod
        name: prometheus-rancher-monitoring-prometheus-0
        namespace: cattle-monitoring-system
        resourceVersion: "6522"
        uid: 49528edb-4c3d-481e-9f44-520fda36020d
    ports:
    - name: nginx-http
      port: 8081
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:55Z"
    creationTimestamp: "2022-03-06T22:52:03Z"
    labels:
      app: prometheus-adapter
      app.kubernetes.io/managed-by: Helm
      chart: prometheus-adapter-2.17.0
      heritage: Helm
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
      release: rancher-monitoring
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:chart: {}
            f:heritage: {}
            f:objectset.rio.cattle.io/hash: {}
            f:release: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:25Z"
    name: rancher-monitoring-prometheus-adapter
    namespace: cattle-monitoring-system
    resourceVersion: "5840"
    uid: 691d70dd-2485-4a37-a99c-b2beff4cffc9
  subsets:
  - addresses:
    - ip: 10.52.0.60
      nodeName: node1
      targetRef:
        kind: Pod
        name: rancher-monitoring-prometheus-adapter-8846d4757-glskx
        namespace: cattle-monitoring-system
        resourceVersion: "5839"
        uid: 1f006475-0769-4c01-bfb6-b19331247aba
    ports:
    - port: 6443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:52:04Z"
    labels:
      app: prometheus-node-exporter
      app.kubernetes.io/managed-by: Helm
      chart: prometheus-node-exporter-2.2.0
      heritage: Helm
      jobLabel: node-exporter
      objectset.rio.cattle.io/hash: a8c87f2d01731fdad3b988f675a7c8a7da10d382
      release: rancher-monitoring
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:chart: {}
            f:heritage: {}
            f:jobLabel: {}
            f:objectset.rio.cattle.io/hash: {}
            f:release: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:57Z"
    name: rancher-monitoring-prometheus-node-exporter
    namespace: cattle-monitoring-system
    resourceVersion: "1026244"
    uid: 7b92adbc-881a-4c93-97c6-86207b3bfe24
  subsets:
  - addresses:
    - ip: 172.16.132.182
      nodeName: node1
      targetRef:
        kind: Pod
        name: rancher-monitoring-prometheus-node-exporter-dsvgt
        namespace: cattle-monitoring-system
        resourceVersion: "5084"
        uid: 5af16d38-9a06-47d4-af7f-9cb3cdf4eca7
    ports:
    - name: metrics
      port: 9796
      protocol: TCP
kind: List
metadata:
  resourceVersion: "14659119"
