apiVersion: v1
items:
- apiVersion: longhorn.io/v1beta1
  kind: Node
  metadata:
    creationTimestamp: "2022-03-06T22:51:51Z"
    finalizers:
    - longhorn.io
    - wrangler.cattle.io/harvester-ndm-node-handler
    generation: 1
    managedFields:
    - apiVersion: longhorn.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"wrangler.cattle.io/harvester-ndm-node-handler"null: {}
      manager: node-disk-manager
      operation: Update
      time: "2022-03-06T22:51:51Z"
    - apiVersion: longhorn.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"longhorn.io"null: {}
        f:spec: {}
        f:status: {}
      manager: longhorn-manager
      operation: Update
      time: "2022-03-06T22:51:53Z"
    name: node1
    namespace: longhorn-system
    resourceVersion: "1109817"
    uid: 29d28350-03f1-4f31-809a-5cd5a1b0ecb2
  spec:
    allowScheduling: true
    disks:
      default-disk-f8d7aaf7a1459bfc:
        allowScheduling: true
        evictionRequested: false
        path: /var/lib/harvester/defaultdisk
        storageReserved: 1.18225516953e+11
        tags: null
    engineManagerCPURequest: 0
    evictionRequested: false
    name: node1
    replicaManagerCPURequest: 0
    tags: []
  status:
    conditions:
      MountPropagation:
        lastProbeTime: "null"
        lastTransitionTime: "2022-03-06T22:51:53Z"
        message: "null"
        reason: "null"
        status: "True"
        type: MountPropagation
      Ready:
        lastProbeTime: "null"
        lastTransitionTime: "2022-03-06T22:51:53Z"
        message: Node node1 is ready
        reason: "null"
        status: "True"
        type: Ready
      Schedulable:
        lastProbeTime: "null"
        lastTransitionTime: "2022-03-06T22:51:53Z"
        message: "null"
        reason: "null"
        status: "True"
        type: Schedulable
    diskStatus:
      default-disk-f8d7aaf7a1459bfc:
        conditions:
          Ready:
            lastProbeTime: "null"
            lastTransitionTime: "2022-03-06T22:51:53Z"
            message: Disk default-disk-f8d7aaf7a1459bfc(/var/lib/harvester/defaultdisk)
              on node node1 is ready
            reason: "null"
            status: "True"
            type: Ready
          Schedulable:
            lastProbeTime: "null"
            lastTransitionTime: "2022-03-06T22:51:53Z"
            message: Disk default-disk-f8d7aaf7a1459bfc(/var/lib/harvester/defaultdisk)
              on node node1 is schedulable
            reason: "null"
            status: "True"
            type: Schedulable
        diskUUID: a3c70e08-bfc1-4915-927a-8a6b80cc12b4
        scheduledReplica: {}
        storageAvailable: 3.93740288e+11
        storageMaximum: 3.94085056512e+11
        storageScheduled: 0
    region: "null"
    zone: "null"
kind: List
metadata:
  continue: "null"
  resourceVersion: "14659230"
