apiVersion: v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    creationTimestamp: "2022-03-06T22:52:22Z"
    generation: 1
    managedFields:
    - apiVersion: policy/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"DisruptionAllowed"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:observedGeneration: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:currentHealthy: {}
          f:desiredHealthy: {}
          f:expectedPods: {}
          f:observedGeneration: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:22Z"
    - apiVersion: policy/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:minAvailable: {}
          f:selector: {}
      manager: longhorn-manager
      operation: Update
      time: "2022-03-06T22:52:22Z"
    name: instance-manager-e-5708ef52
    namespace: longhorn-system
    resourceVersion: "5146"
    uid: 6d82baa7-40af-45da-b03f-ea4e507d9eca
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        longhorn.io/component: instance-manager
        longhorn.io/instance-manager-image: imi-2ff8743e
        longhorn.io/instance-manager-type: engine
        longhorn.io/managed-by: longhorn-manager
        longhorn.io/node: node1
  status:
    conditions:
    - lastTransitionTime: "2022-03-06T22:52:22Z"
      message: "null"
      observedGeneration: 1
      reason: InsufficientPods
      status: "False"
      type: DisruptionAllowed
    currentHealthy: 1
    desiredHealthy: 1
    disruptionsAllowed: 0
    expectedPods: 1
    observedGeneration: 1
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    creationTimestamp: "2022-03-06T22:52:23Z"
    generation: 1
    managedFields:
    - apiVersion: policy/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"DisruptionAllowed"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:observedGeneration: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:currentHealthy: {}
          f:desiredHealthy: {}
          f:expectedPods: {}
          f:observedGeneration: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:23Z"
    - apiVersion: policy/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:minAvailable: {}
          f:selector: {}
      manager: longhorn-manager
      operation: Update
      time: "2022-03-06T22:52:23Z"
    name: instance-manager-r-9d910deb
    namespace: longhorn-system
    resourceVersion: "5162"
    uid: 9a374646-5f79-4d8d-a801-2f736efe5c4d
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        longhorn.io/component: instance-manager
        longhorn.io/instance-manager-image: imi-2ff8743e
        longhorn.io/instance-manager-type: replica
        longhorn.io/managed-by: longhorn-manager
        longhorn.io/node: node1
  status:
    conditions:
    - lastTransitionTime: "2022-03-06T22:52:23Z"
      message: "null"
      observedGeneration: 1
      reason: InsufficientPods
      status: "False"
      type: DisruptionAllowed
    currentHealthy: 1
    desiredHealthy: 1
    disruptionsAllowed: 0
    expectedPods: 1
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: "14659220"
