apiVersion: v1
items:
- apiVersion: k3s.cattle.io/v1
  kind: Addon
  metadata:
    creationTimestamp: "2022-03-06T22:50:43Z"
    generation: 1
    managedFields:
    - apiVersion: k3s.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec: {}
        f:status: {}
      manager: deploy@node1
      operation: Update
      time: "2022-03-06T22:50:43Z"
    name: addons
    namespace: kube-system
    resourceVersion: "3439"
    uid: 16a576f7-cb0c-40f4-a2c2-290aec6da1ed
  spec:
    source: /var/lib/rancher/rke2/server/manifests/rancher/addons.yaml
  status: {}
- apiVersion: k3s.cattle.io/v1
  kind: Addon
  metadata:
    creationTimestamp: "2022-03-06T22:50:43Z"
    generation: 1
    managedFields:
    - apiVersion: k3s.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec: {}
        f:status: {}
      manager: deploy@node1
      operation: Update
      time: "2022-03-06T22:50:43Z"
    name: cluster-agent
    namespace: kube-system
    resourceVersion: "3449"
    uid: 71d182f4-38f7-492c-91f8-260881579498
  spec:
    source: /var/lib/rancher/rke2/server/manifests/rancher/cluster-agent.yaml
  status: {}
- apiVersion: k3s.cattle.io/v1
  kind: Addon
  metadata:
    creationTimestamp: "2022-03-06T22:50:44Z"
    generation: 1
    managedFields:
    - apiVersion: k3s.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec: {}
        f:status: {}
      manager: deploy@node1
      operation: Update
      time: "2022-03-06T22:50:44Z"
    name: managed-chart-config
    namespace: kube-system
    resourceVersion: "3460"
    uid: ec8d94d9-99dd-4014-97de-2ecec264083e
  spec:
    source: /var/lib/rancher/rke2/server/manifests/rancher/managed-chart-config.yaml
  status: {}
- apiVersion: k3s.cattle.io/v1
  kind: Addon
  metadata:
    creationTimestamp: "2022-03-06T22:46:56Z"
    generation: 1
    managedFields:
    - apiVersion: k3s.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec: {}
        f:status: {}
      manager: deploy@node1
      operation: Update
      time: "2022-03-06T22:46:56Z"
    name: rke2-canal
    namespace: kube-system
    resourceVersion: "265"
    uid: 32068d4a-2715-4180-a1a9-63784571f555
  spec:
    source: /var/lib/rancher/rke2/server/manifests/rke2-canal.yaml
  status: {}
- apiVersion: k3s.cattle.io/v1
  kind: Addon
  metadata:
    creationTimestamp: "2022-03-06T22:46:56Z"
    generation: 1
    managedFields:
    - apiVersion: k3s.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec: {}
        f:status: {}
      manager: deploy@node1
      operation: Update
      time: "2022-03-06T22:46:56Z"
    name: rke2-canal-config
    namespace: kube-system
    resourceVersion: "262"
    uid: 416f006e-1d66-4855-aa94-bb69bac75a2b
  spec:
    source: /var/lib/rancher/rke2/server/manifests/rke2-canal-config.yaml
  status: {}
- apiVersion: k3s.cattle.io/v1
  kind: Addon
  metadata:
    creationTimestamp: "2022-03-06T22:46:56Z"
    generation: 1
    managedFields:
    - apiVersion: k3s.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec: {}
        f:status: {}
      manager: deploy@node1
      operation: Update
      time: "2022-03-06T22:46:56Z"
    name: rke2-coredns
    namespace: kube-system
    resourceVersion: "281"
    uid: d9b50333-90fd-4ce8-a350-1d529cb002d1
  spec:
    source: /var/lib/rancher/rke2/server/manifests/rke2-coredns.yaml
  status: {}
- apiVersion: k3s.cattle.io/v1
  kind: Addon
  metadata:
    creationTimestamp: "2022-03-06T22:46:56Z"
    generation: 1
    managedFields:
    - apiVersion: k3s.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec: {}
        f:status: {}
      manager: deploy@node1
      operation: Update
      time: "2022-03-06T22:46:56Z"
    name: rke2-ingress-nginx
    namespace: kube-system
    resourceVersion: "288"
    uid: c5b217e2-344d-411e-8c85-6efe65253ba3
  spec:
    source: /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx.yaml
  status: {}
- apiVersion: k3s.cattle.io/v1
  kind: Addon
  metadata:
    creationTimestamp: "2022-03-06T22:46:57Z"
    generation: 1
    managedFields:
    - apiVersion: k3s.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec: {}
        f:status: {}
      manager: deploy@node1
      operation: Update
      time: "2022-03-06T22:46:57Z"
    name: rke2-metrics-server
    namespace: kube-system
    resourceVersion: "332"
    uid: e7521f28-d9e9-421b-b858-d8af0347f274
  spec:
    source: /var/lib/rancher/rke2/server/manifests/rke2-metrics-server.yaml
  status: {}
- apiVersion: k3s.cattle.io/v1
  kind: Addon
  metadata:
    creationTimestamp: "2022-03-06T22:46:57Z"
    generation: 1
    managedFields:
    - apiVersion: k3s.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec: {}
        f:status: {}
      manager: deploy@node1
      operation: Update
      time: "2022-03-06T22:46:57Z"
    name: rke2-multus
    namespace: kube-system
    resourceVersion: "377"
    uid: 985bc5c2-8180-4108-9c48-3a33f91252da
  spec:
    source: /var/lib/rancher/rke2/server/manifests/rke2-multus.yaml
  status: {}
kind: List
metadata:
  continue: "null"
  resourceVersion: "14659003"
