apiVersion: v1
items:
- apiVersion: management.cattle.io/v3
  kind: Feature
  metadata:
    creationTimestamp: "2022-03-06T22:48:40Z"
    generation: 1
    managedFields:
    - apiVersion: management.cattle.io/v3
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:value: {}
        f:status:
          .: {}
          f:default: {}
          f:description: {}
          f:dynamic: {}
          f:lockedValue: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:48:40Z"
    name: continuous-delivery
    resourceVersion: "1215"
    uid: baaa3f19-4498-4ece-b2dd-9a7a94d1ef7d
  spec:
    value: null
  status:
    default: true
    description: Gitops components in fleet
    dynamic: false
    lockedValue: null
- apiVersion: management.cattle.io/v3
  kind: Feature
  metadata:
    creationTimestamp: "2022-03-06T22:48:40Z"
    generation: 1
    managedFields:
    - apiVersion: management.cattle.io/v3
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:value: {}
        f:status:
          .: {}
          f:default: {}
          f:description: {}
          f:dynamic: {}
          f:lockedValue: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:48:40Z"
    name: fleet
    resourceVersion: "1221"
    uid: a719163c-2e30-4291-8b92-a04346ff9d4a
  spec:
    value: null
  status:
    default: true
    description: Install Fleet when starting Rancher
    dynamic: false
    lockedValue: null
- apiVersion: management.cattle.io/v3
  kind: Feature
  metadata:
    creationTimestamp: "2022-03-06T22:48:41Z"
    generation: 1
    managedFields:
    - apiVersion: management.cattle.io/v3
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:value: {}
        f:status:
          .: {}
          f:default: {}
          f:description: {}
          f:dynamic: {}
          f:lockedValue: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:48:41Z"
    name: harvester
    resourceVersion: "1223"
    uid: 5b6d93b4-1072-4e9e-8699-6fd7ae9fbfc4
  spec:
    value: null
  status:
    default: true
    description: Enable Harvester integration, with ability to import and manage Harvester
      clusters
    dynamic: true
    lockedValue: null
- apiVersion: management.cattle.io/v3
  kind: Feature
  metadata:
    creationTimestamp: "2022-03-06T22:48:40Z"
    generation: 1
    managedFields:
    - apiVersion: management.cattle.io/v3
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:value: {}
        f:status:
          .: {}
          f:default: {}
          f:description: {}
          f:dynamic: {}
          f:lockedValue: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:48:40Z"
    name: istio-virtual-service-ui
    resourceVersion: "1217"
    uid: 9850aef2-1069-49de-b16a-d19b2da63235
  spec:
    value: null
  status:
    default: true
    description: Exposes a UI that enables users to create, read, update and delete
      virtual services and destination rules, which are traffic management features
      of Istio.
    dynamic: true
    lockedValue: null
- apiVersion: management.cattle.io/v3
  kind: Feature
  metadata:
    creationTimestamp: "2022-03-06T22:48:40Z"
    generation: 1
    managedFields:
    - apiVersion: management.cattle.io/v3
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:value: {}
        f:status:
          .: {}
          f:default: {}
          f:description: {}
          f:dynamic: {}
          f:lockedValue: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:48:40Z"
    name: legacy
    resourceVersion: "1216"
    uid: 4f1e396d-d78c-4943-a5d1-dcc51d02a7f0
  spec:
    value: null
  status:
    default: false
    description: Enable legacy features
    dynamic: true
    lockedValue: null
- apiVersion: management.cattle.io/v3
  kind: Feature
  metadata:
    creationTimestamp: "2022-03-06T22:48:40Z"
    generation: 1
    managedFields:
    - apiVersion: management.cattle.io/v3
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:value: {}
        f:status:
          .: {}
          f:default: {}
          f:description: {}
          f:dynamic: {}
          f:lockedValue: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:48:40Z"
    name: multi-cluster-management
    resourceVersion: "1220"
    uid: 535fd971-df63-477e-9c09-28e6d4f11a71
  spec:
    value: null
  status:
    default: false
    description: Multi-cluster provisioning and management of Kubernetes clusters.
    dynamic: false
    lockedValue: null
- apiVersion: management.cattle.io/v3
  kind: Feature
  metadata:
    creationTimestamp: "2022-03-06T22:48:40Z"
    generation: 1
    managedFields:
    - apiVersion: management.cattle.io/v3
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:value: {}
        f:status:
          .: {}
          f:default: {}
          f:description: {}
          f:dynamic: {}
          f:lockedValue: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:48:40Z"
    name: rke2
    resourceVersion: "1222"
    uid: 0d12e70d-9712-4e71-9df6-a642e4269f99
  spec:
    value: null
  status:
    default: true
    description: Enable provisioning of RKE2
    dynamic: false
    lockedValue: null
- apiVersion: management.cattle.io/v3
  kind: Feature
  metadata:
    creationTimestamp: "2022-03-06T22:48:40Z"
    generation: 1
    managedFields:
    - apiVersion: management.cattle.io/v3
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:value: {}
        f:status:
          .: {}
          f:default: {}
          f:description: {}
          f:dynamic: {}
          f:lockedValue: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:48:40Z"
    name: token-hashing
    resourceVersion: "1218"
    uid: c351fb66-80f4-4928-8bba-9c86ad6fb31c
  spec:
    value: null
  status:
    default: false
    description: Enable one way hashing of tokens. Once enabled token hashing can
      not be disabled
    dynamic: true
    lockedValue: null
- apiVersion: management.cattle.io/v3
  kind: Feature
  metadata:
    creationTimestamp: "2022-03-06T22:48:40Z"
    generation: 1
    managedFields:
    - apiVersion: management.cattle.io/v3
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:value: {}
        f:status:
          .: {}
          f:default: {}
          f:description: {}
          f:dynamic: {}
          f:lockedValue: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:48:40Z"
    name: unsupported-storage-drivers
    resourceVersion: "1219"
    uid: 817d3cb4-0157-4670-aac8-9e3dd7400779
  spec:
    value: null
  status:
    default: false
    description: Allows the use of types for storage providers and provisioners that
      are not enabled by default.
    dynamic: true
    lockedValue: null
kind: List
metadata:
  continue: "null"
  resourceVersion: "14658916"
