apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: CSINode
  metadata:
    annotations:
      storage.alpha.kubernetes.io/migrated-plugins: kubernetes.io/cinder
    creationTimestamp: "2022-03-06T22:46:51Z"
    managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:storage.alpha.kubernetes.io/migrated-plugins: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"c4cd362a-7999-46e3-8744-b65c1581fd4e"}:
              .: {}
              f:apiVersion: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:spec:
          f:drivers:
            k:{"name":"driver.longhorn.io"}:
              .: {}
              f:name: {}
              f:nodeID: {}
              f:topologyKeys: {}
      manager: kubelet
      operation: Update
      time: "2022-03-06T22:52:22Z"
    name: node1
    ownerReferences:
    - apiVersion: v1
      kind: Node
      name: node1
      uid: c4cd362a-7999-46e3-8744-b65c1581fd4e
    resourceVersion: "5133"
    uid: 8cda9266-5073-4c05-a2e6-c6ac83fd9221
  spec:
    drivers:
    - name: driver.longhorn.io
      nodeID: node1
      topologyKeys: null
kind: List
metadata:
  resourceVersion: "14658870"
