apiVersion: v1
items:
- apiVersion: fleet.cattle.io/v1alpha1
  kind: ClusterGroup
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3xOTU7zMBC9y6z79WtDmlDvULesEBeY2hNisD2WPVZVVbk7sluKhBC7N2/e3wU8CRoUBHUBDIEFxXLI9eTjO2nJJOtkea1RxNHa8n9rQMHkiOTfkVmyJIywrEAnauZX6ykL+ggqFOdW4PBI7s/IGfMMCoZx6sfdNHQD7frxYRy7adg89tjtt9txg3tDu33fmW1tC+gJFBiasDiBK5Ejarqvc6zRVW2OpGt9JkdaOFXsUfT8fF92i7tZlmoSlNJ+2pUslA5cgoDarMDYHB2eQV3qEA4vhOZ8+KlKlLkkTY1pQYayTWSavEm8zdmGtytmYydLph2B5VvFKc4Ybp90p0v4CHwKDZ/QylOM7uqv64v3mM6/tn5FLMvyGQAA///yPuq4AQIAAA
      objectset.rio.cattle.io/id: fleet-bootstrap
    creationTimestamp: "2022-03-06T22:49:22Z"
    generation: 1
    labels:
      objectset.rio.cattle.io/hash: 67f475f626e5473772f6084a291170a9de5942d1
    managedFields:
    - apiVersion: fleet.cattle.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
        f:spec:
          .: {}
          f:selector:
            .: {}
            f:matchLabels:
              .: {}
              f:name: {}
        f:status:
          .: {}
          f:clusterCount: {}
          f:conditions: {}
          f:display:
            .: {}
            f:readyBundles: {}
            f:readyClusters: {}
          f:nonReadyClusterCount: {}
          f:resourceCounts:
            .: {}
            f:desiredReady: {}
            f:missing: {}
            f:modified: {}
            f:notReady: {}
            f:orphaned: {}
            f:ready: {}
            f:unknown: {}
            f:waitApplied: {}
          f:summary:
            .: {}
            f:desiredReady: {}
            f:ready: {}
      manager: fleetcontroller
      operation: Update
      time: "2022-03-22T18:54:11Z"
    name: default
    namespace: fleet-local
    resourceVersion: "14472032"
    uid: 3a4809a3-6d95-45ba-952a-fe5cd8ce5504
  spec:
    selector:
      matchLabels:
        name: local
  status:
    clusterCount: 0
    conditions:
    - lastUpdateTime: "2022-03-22T18:54:11Z"
      status: "True"
      type: Ready
    - lastUpdateTime: "2022-03-22T18:54:11Z"
      status: "True"
      type: Processed
    display:
      readyBundles: 0/0
      readyClusters: 0/0
    nonReadyClusterCount: 0
    resourceCounts:
      desiredReady: 0
      missing: 0
      modified: 0
      notReady: 0
      orphaned: 0
      ready: 0
      unknown: 0
      waitApplied: 0
    summary:
      desiredReady: 0
      ready: 0
kind: List
metadata:
  continue: "null"
  resourceVersion: "14659166"
