apiVersion: v1
items:
- apiVersion: provisioning.cattle.io/v1
  kind: Cluster
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"provisioning.cattle.io/v1","kind":"Cluster","metadata":{"annotations":{},"labels":{"rke.cattle.io/init-node-machine-id":"cscftk2nzms6pn4tfp5rpkxd7n5cdrpww768h7scqxvh8glw4mrdpk"},"name":"local","namespace":"fleet-local"},"spec":{"kubernetesVersion":"v1.21.7+rke2r1","rkeConfig":{"controlPlaneConfig":null}}}
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQzU7DMBCEXwXt2Slt079Y4oAQ4sCVF9jYS2Ow15G9CYfK746SVqJC4udo78xovjlBIEGLgqBPgMxRUFzkPD1j+0ZGMskiubgwKOJp4eKts6ChT3F02UV2fKyMH7JQqkwiFAL1ozV+MKXqOL6DhoCMRwrEciUYa3Xz7NjePZwj/8xiDAQafDTo/yXOPZrJAUXB3NdFfnGBsmDoQfPgvQKPLflfR+gwd6Bhu9ztt3XdUGNwc7Crdr9u6jW1y/pg91vb2LXdbHarA6jzYpbSVwho6DCNNIMWBd9Yrtu+eiKpzpeiIPdkpnbzx2Wq+0G6R7Z9dCygT2WSCcpwwciURrJPxJRmZtDLUj4DAAD//5CVWGcAAgAA
      objectset.rio.cattle.io/id: provisioning-cluster-create
      objectset.rio.cattle.io/owner-gvk: management.cattle.io/v3, Kind=Cluster
      objectset.rio.cattle.io/owner-name: local
      objectset.rio.cattle.io/owner-namespace: "null"
    creationTimestamp: "2022-03-06T22:48:49Z"
    finalizers:
    - wrangler.cattle.io/provisioning-cluster-remove
    generation: 2
    labels:
      objectset.rio.cattle.io/hash: 50675339e9ca48d1b72932eb038d75d9d2d44618
      provider.cattle.io: harvester
      rke.cattle.io/init-node-machine-id: cscftk2nzms6pn4tfp5rpkxd7n5cdrpww768h7scqxvh8glw4mrdpk
    managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/provisioning-cluster-remove"null: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
            f:provider.cattle.io: {}
        f:spec:
          .: {}
          f:localClusterAuthEndpoint: {}
        f:status:
          .: {}
          f:clientSecretName: {}
          f:clusterName: {}
          f:conditions: {}
          f:observedGeneration: {}
          f:ready: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:48:50Z"
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            f:rke.cattle.io/init-node-machine-id: {}
        f:spec:
          f:kubernetesVersion: {}
          f:rkeConfig: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2022-03-06T22:49:42Z"
    name: local
    namespace: fleet-local
    resourceVersion: "870938"
    uid: e8daa158-40df-4369-a8b2-716290f66a22
  spec:
    kubernetesVersion: v1.21.7+rke2r1
    localClusterAuthEndpoint: {}
    rkeConfig: {}
  status:
    clientSecretName: local-kubeconfig
    clusterName: local
    conditions:
    - status: "True"
      type: Ready
    - lastUpdateTime: "2022-03-06T22:48:49Z"
      status: "False"
      type: Reconciling
    - lastUpdateTime: "2022-03-06T22:48:49Z"
      status: "False"
      type: Stalled
    - lastUpdateTime: "2022-03-06T22:49:42Z"
      status: "True"
      type: Created
    - lastUpdateTime: "2022-03-07T22:12:42Z"
      status: "True"
      type: RKECluster
    - status: Unknown
      type: DefaultProjectCreated
    - status: Unknown
      type: SystemProjectCreated
    - lastUpdateTime: "2022-03-07T22:12:42Z"
      status: "True"
      type: Provisioned
    observedGeneration: 2
    ready: true
kind: List
metadata:
  continue: "null"
  resourceVersion: "14659164"
