apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2022-03-07T22:16:08Z"
    labels:
      authz.cluster.cattle.io/rtb-owner-updated: p-qwrnd_creator-project-owner
      cattle.io/creator: norman
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:authz.cluster.cattle.io/rtb-owner-updated: {}
            f:cattle.io/creator: {}
        f:roleRef:
          f:apiGroup: {}
          f:kind: {}
          f:name: {}
        f:subjects: {}
      manager: rancher
      operation: Update
      time: "2022-03-07T22:16:08Z"
    name: rb-74rknsqm3x
    namespace: default
    resourceVersion: "874938"
    uid: 19bdb717-015c-4248-b3c5-1b564aea80c6
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: project-owner
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: user-4dqnw
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2022-03-07T22:16:08Z"
    labels:
      authz.cluster.cattle.io/rtb-owner-updated: p-qwrnd_creator-project-owner
      cattle.io/creator: norman
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:authz.cluster.cattle.io/rtb-owner-updated: {}
            f:cattle.io/creator: {}
        f:roleRef:
          f:apiGroup: {}
          f:kind: {}
          f:name: {}
        f:subjects: {}
      manager: rancher
      operation: Update
      time: "2022-03-07T22:16:08Z"
    name: rb-fjkkf7us5k
    namespace: default
    resourceVersion: "874946"
    uid: b9ea4260-de8a-442e-b030-3a97f4c89f5a
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: user-4dqnw
kind: List
metadata:
  resourceVersion: "14658980"
