apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 172.16.132.182
    conditions:
      ready: true
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2022-03-06T22:46:54Z"
    generation: 1
    labels:
      kubernetes.io/service-name: kubernetes
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:labels:
            .: {}
            f:kubernetes.io/service-name: {}
        f:ports: {}
      manager: kube-apiserver
      operation: Update
      time: "2022-03-06T22:46:54Z"
    name: kubernetes
    namespace: default
    resourceVersion: "212"
    uid: bda5ae99-170e-4723-86d8-76d272c30745
  ports:
  - name: https
    port: 6443
    protocol: TCP
kind: List
metadata:
  resourceVersion: "14658980"
