apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBejCCAR+gAwIBAgIBADAKBggqhkjOPQQDAjAkMSIwIAYDVQQDDBlya2UyLXNl
      cnZlci1jYUAxNjQ2NjA2NzYxMB4XDTIyMDMwNjIyNDYwMVoXDTMyMDMwMzIyNDYw
      MVowJDEiMCAGA1UEAwwZcmtlMi1zZXJ2ZXItY2FAMTY0NjYwNjc2MTBZMBMGByqG
      SM49AgEGCCqGSM49AwEHA0IABH+0BOq7FJij86zAjeedEnaJ+TkxCjFNcDBoo/R5
      XIuYHfO3cCeVIuvO6X//Rep7MG+bcbTenCP4RhwDHYKD+J2jQjBAMA4GA1UdDwEB
      /wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRBQ79Om8U8JEONqyG+
      21eN8KmH1DAKBggqhkjOPQQDAgNJADBGAiEAsNa9lXUL4SA4WC6P4v6yDCTILlZA
      yB4jTWBnW24PB/gCIQCv7238+JiviH9sFUWdFE2zxZ3AGLyPkwCcj/7ZppcWRA==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    creationTimestamp: "2022-03-06T22:48:48Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:48:48Z"
    name: kube-root-ca.crt
    namespace: local
    resourceVersion: "1463"
    uid: c7f46c6e-0173-447d-add4-e876f06a5b8f
kind: List
metadata:
  resourceVersion: "14659208"
