apiVersion: v1
items:
- apiVersion: cluster.x-k8s.io/v1alpha4
  kind: Cluster
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5ySQY/TMBCF/wqas7MkafEmljgte9oDqEJcEIexPdmauHZkT4pQlf+OHBZRClutONp6z+/NNz7BgRgtMoI6AYYQGdnFkMsx6q9kOBPfJBdvDDJ7unHxtbOgII1UGT9npgTiWWn8FihVj8cRFEwpHl12MbjweCY5NuLVgwv27d0LXwt4IFDgo0H/InGe0BTH4Im4+ulbBJhE66wf3YEy42ECFWbvBXjU5K8S2GPeg4Km7qTUndabre5Jkqnb7WaoTVf30liNtuktydu+pF20fq6XgLX3jgZKFAxlUJ9PgJP7RKmwu8YRBGgfzfi+vPCOPPFq4DSTABMDp+g9pV83owtlkb+xX1Sc1z1TZxGbN121re1QbTeyr7DTbXXbyLavBymxbWH5sgjIE5kC7Snpg8dA98FO0QUu9/uYGRSAgCkmBlUv4g/tjob1E57Pmka6HPGp9u7h/u7M/Hf9K5t3YUiYOc2G5/Qfuf8mthQGjDyvX+cyA+13UAP6TMvyIwAA//+D1BUsdgMAAA
      objectset.rio.cattle.io/id: rke-cluster
      objectset.rio.cattle.io/owner-gvk: provisioning.cattle.io/v1, Kind=Cluster
      objectset.rio.cattle.io/owner-name: local
      objectset.rio.cattle.io/owner-namespace: fleet-local
    creationTimestamp: "2022-03-06T22:50:04Z"
    finalizers:
    - cluster.cluster.x-k8s.io
    generation: 266
    labels:
      objectset.rio.cattle.io/hash: 10866b8bb34b9e6ec0243f0c8096cdbad19de679
    managedFields:
    - apiVersion: cluster.x-k8s.io/v1alpha4
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
          f:finalizers:
            .: {}
            v:"cluster.cluster.x-k8s.io"null: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"e8daa158-40df-4369-a8b2-716290f66a22"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:spec:
          .: {}
          f:controlPlaneEndpoint:
            .: {}
            f:host: {}
            f:port: {}
          f:controlPlaneRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
          f:infrastructureRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
        f:status:
          .: {}
          f:conditions: {}
          f:controlPlaneReady: {}
          f:infrastructureReady: {}
          f:observedGeneration: {}
          f:phase: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:50:04Z"
    name: local
    namespace: fleet-local
    ownerReferences:
    - apiVersion: provisioning.cattle.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Cluster
      name: local
      uid: e8daa158-40df-4369-a8b2-716290f66a22
    resourceVersion: "14472237"
    uid: 4f4994b3-6e9b-43ca-ad0a-e9b841cd3ee6
  spec:
    controlPlaneEndpoint:
      host: localhost
      port: 6443
    controlPlaneRef:
      apiVersion: rke.cattle.io/v1
      kind: RKEControlPlane
      name: local
      namespace: fleet-local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: RKECluster
      name: local
      namespace: fleet-local
  status:
    conditions:
    - lastTransitionTime: "2022-03-07T22:12:41Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2022-03-06T22:50:04Z"
      message: Waiting for control plane provider to indicate the control plane has
        been initialized
      reason: WaitingForControlPlaneProviderInitialized
      severity: Info
      status: "False"
      type: ControlPlaneInitialized
    - lastTransitionTime: "2022-03-06T22:50:04Z"
      status: "True"
      type: ControlPlaneReady
    - lastTransitionTime: "2022-03-07T22:12:41Z"
      status: "True"
      type: InfrastructureReady
    controlPlaneReady: true
    infrastructureReady: true
    observedGeneration: 266
    phase: Provisioned
kind: List
metadata:
  continue: "null"
  resourceVersion: "14659167"
