apiVersion: v1
items:
- apiVersion: cluster.x-k8s.io/v1alpha4
  kind: Machine
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5yST5PTMAzFvwqjc9JtafOnmeECw2kHDoXhrshyY+LYxlaahZ1+dyZdpuzSobB7VKIn/96T7mFgQYWC0NwDOucFxXiX5tK3X5kksSyi8QtCEcsL42+MggZGN6DDPat8QOqMY8j+KvCT45jvDz00cHNYZa9ujVNvPjFFln/KHA4MDdCYxA85rZdUrFalWin8L2kKSLPeekILxwwo8sniZzNwEhwCNG60NgOLLdurxjtMHTRQl2qjSs1bpmqp1m2tl8Va1XVRLdV2zdutrkuq2hoyiD0/0pN3Er3Ng0XHefR2BpM48kUnC6mrDb9Cz0+7oERa+tfux5DK4DaiQxFDf6cqV5CKYZqqsu6qRN/uDl29t9NmiCr0FzMnH3uOT549ZnA1/8cJa8ss+TnnFJjmMFvvJUnEMBfknTb7HevTuQXzhWMy3kHzB8phBRn0xs3udrfv355nvJRnXrwdk3D8+KB/+J6BcTpikjiSjJGfR/buxPDhfP8vRkuCMqYnae0Y1XdoNNrEl5S//x2PPwMAAP//c22XdcQDAAA
      objectset.rio.cattle.io/id: unmanaged-machine
      objectset.rio.cattle.io/owner-gvk: /v1, Kind=Secret
      objectset.rio.cattle.io/owner-name: custom-c30c5116d1da
      objectset.rio.cattle.io/owner-namespace: local
      rke.cattle.io/join-url: https://172.16.132.182:9345
    creationTimestamp: "2022-03-06T22:50:21Z"
    finalizers:
    - machine.cluster.x-k8s.io
    generation: 3
    labels:
      cluster.x-k8s.io/cluster-name: local
      objectset.rio.cattle.io/hash: 86d4d6fe9ec70d3b8f053d88570d93e99f86c7b8
      rke.cattle.io/control-plane-role: "true"
      rke.cattle.io/etcd-role: "true"
      rke.cattle.io/init-node: "true"
      rke.cattle.io/machine-id: cscftk2nzms6pn4tfp5rpkxd7n5cdrpww768h7scqxvh8glw4mrdpk
      rke.cattle.io/worker-role: "true"
    managedFields:
    - apiVersion: cluster.x-k8s.io/v1alpha4
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:rke.cattle.io/join-url: {}
          f:finalizers:
            .: {}
            v:"machine.cluster.x-k8s.io"null: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
            f:rke.cattle.io/control-plane-role: {}
            f:rke.cattle.io/etcd-role: {}
            f:rke.cattle.io/init-node: {}
            f:rke.cattle.io/machine-id: {}
            f:rke.cattle.io/worker-role: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4f4994b3-6e9b-43ca-ad0a-e9b841cd3ee6"}:
              .: {}
              f:apiVersion: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:spec:
          .: {}
          f:bootstrap:
            .: {}
            f:configRef:
              .: {}
              f:apiVersion: {}
              f:kind: {}
              f:name: {}
              f:namespace: {}
            f:dataSecretName: {}
          f:clusterName: {}
          f:infrastructureRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
          f:providerID: {}
        f:status:
          .: {}
          f:addresses: {}
          f:bootstrapReady: {}
          f:conditions: {}
          f:infrastructureReady: {}
          f:lastUpdated: {}
          f:nodeInfo:
            .: {}
            f:architecture: {}
            f:bootID: {}
            f:containerRuntimeVersion: {}
            f:kernelVersion: {}
            f:kubeProxyVersion: {}
            f:kubeletVersion: {}
            f:machineID: {}
            f:operatingSystem: {}
            f:osImage: {}
            f:systemUUID: {}
          f:nodeRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
          f:observedGeneration: {}
          f:phase: {}
      manager: rancher
      operation: Update
      time: "2022-03-06T22:51:03Z"
    name: custom-c30c5116d1da
    namespace: fleet-local
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1alpha4
      kind: Cluster
      name: local
      uid: 4f4994b3-6e9b-43ca-ad0a-e9b841cd3ee6
    resourceVersion: "3804"
    uid: e5f54ba4-68bd-4dcb-a99b-ccff27446c3d
  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: custom-c30c5116d1da
        namespace: fleet-local
      dataSecretName: custom-c30c5116d1da-machine-bootstrap
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-c30c5116d1da
      namespace: fleet-local
    providerID: rke2://node1
  status:
    addresses:
    - address: 172.16.132.182
      type: InternalIP
    - address: node1
      type: Hostname
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2022-03-06T22:51:03Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2022-03-06T22:50:22Z"
      status: "True"
      type: BootstrapReady
    - lastTransitionTime: "2022-03-06T22:51:03Z"
      status: "True"
      type: InfrastructureReady
    - lastTransitionTime: "2022-03-06T22:51:22Z"
      status: "True"
      type: NodeHealthy
    - lastTransitionTime: "2022-03-06T22:51:22Z"
      message: plan applied
      reason: InSync
      severity: Info
      status: "True"
      type: Provisioned
    infrastructureReady: true
    lastUpdated: "2022-03-06T22:51:03Z"
    nodeInfo:
      architecture: amd64
      bootID: 3b9e6129-5a49-4dff-add3-d6129ac01acb
      containerRuntimeVersion: containerd://1.4.12-k3s1
      kernelVersion: 5.3.18-59.37-default
      kubeProxyVersion: v1.21.7+rke2r1
      kubeletVersion: v1.21.7+rke2r1
      machineID: b0bae580f1b2b604f3d1dbe762253720
      operatingSystem: linux
      osImage: Harvester ada3f1a-dirty
      systemUUID: b0bae580f1b2b604f3d1dbe762253720
    nodeRef:
      apiVersion: v1
      kind: Node
      name: node1
      uid: c4cd362a-7999-46e3-8744-b65c1581fd4e
    observedGeneration: 3
    phase: Running
kind: List
metadata:
  continue: "null"
  resourceVersion: "14659167"
