apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.26
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: harvester-webhook-67744f845f-5msj8
      namespace: harvester-system
      resourceVersion: "4073"
      uid: feb4b9e8-7f24-4fce-a106-2e57e147e4c1
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2022-03-06T22:50:37Z"
    generateName: harvester-webhook-
    generation: 7
    labels:
      app.kubernetes.io/managed-by: Helm
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: harvester-webhook
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"2f04465e-c165-4a35-8780-8f8d45aa9bd4"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:06Z"
    name: harvester-webhook-6zmgd
    namespace: harvester-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: harvester-webhook
      uid: 2f04465e-c165-4a35-8780-8f8d45aa9bd4
    resourceVersion: "1025060"
    uid: ba08d9e1-8564-419a-a9a1-3bc40d3c579d
  ports:
  - name: https
    port: 9443
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.38
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: harvester-d544ddb6f-6g2fl
      namespace: harvester-system
      resourceVersion: "4096"
      uid: fd0be963-a9d7-43cc-ba33-755951faefaa
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2022-03-06T22:50:37Z"
    generateName: harvester-
    generation: 7
    labels:
      app.kubernetes.io/component: apiserver
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: harvester
      app.kubernetes.io/part-of: harvester
      app.kubernetes.io/version: 0.1.x
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: harvester-0.0.0-dev
      helm.sh/release: harvester
      kubernetes.io/cluster-service: "true"
      kubernetes.io/service-name: harvester
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:helm.sh/chart: {}
            f:helm.sh/release: {}
            f:kubernetes.io/cluster-service: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"e714f16b-2d0a-4031-941d-9d5d2d27751d"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:06Z"
    name: harvester-xnxvs
    namespace: harvester-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: harvester
      uid: e714f16b-2d0a-4031-941d-9d5d2d27751d
    resourceVersion: "1025038"
    uid: f3970f02-dc83-4b44-adac-87605ee6d552
  ports:
  - name: https
    port: 8443
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.34
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: virt-operator-56c5bdc7b8-jqntd
      namespace: harvester-system
      resourceVersion: "4895"
      uid: d1bc3106-d8c7-4169-93ac-b175c18eecc4
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:50Z"
    creationTimestamp: "2022-03-06T22:52:50Z"
    generateName: kubevirt-operator-webhook-
    generation: 1
    labels:
      app.kubernetes.io/component: kubevirt
      app.kubernetes.io/managed-by: kubevirt-operator
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: kubevirt-operator-webhook
      kubevirt.io: "null"
      prometheus.kubevirt.io: "null"
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:kubernetes.io/service-name: {}
            f:kubevirt.io: {}
            f:prometheus.kubevirt.io: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"3a3af958-5493-421f-b92a-d6e84a9672cb"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:50Z"
    name: kubevirt-operator-webhook-twj2w
    namespace: harvester-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: kubevirt-operator-webhook
      uid: 3a3af958-5493-421f-b92a-d6e84a9672cb
    resourceVersion: "5753"
    uid: 276bf32f-34ee-43e9-ba73-c27abdc4908e
  ports:
  - name: webhooks
    port: 8444
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.34
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: virt-operator-56c5bdc7b8-jqntd
      namespace: harvester-system
      resourceVersion: "4895"
      uid: d1bc3106-d8c7-4169-93ac-b175c18eecc4
  - addresses:
    - 10.52.0.66
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: virt-api-86455cdb7d-mdk4m
      namespace: harvester-system
      resourceVersion: "6189"
      uid: 7a98124d-1ba4-4711-a391-7225c655f9f2
  - addresses:
    - 10.52.0.67
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: virt-api-86455cdb7d-khcv5
      namespace: harvester-system
      resourceVersion: "6181"
      uid: 326c914e-4e0d-461b-b3fc-87af92bafd1f
  - addresses:
    - 10.52.0.72
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: virt-controller-5f649999dd-5lw26
      namespace: harvester-system
      resourceVersion: "6853"
      uid: 222e8519-621a-4c66-9cff-5e6ea45d012c
  - addresses:
    - 10.52.0.71
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: virt-controller-5f649999dd-j5qpd
      namespace: harvester-system
      resourceVersion: "6847"
      uid: 76c4f877-c8cd-4925-9145-fb8b8f365d9a
  - addresses:
    - 10.52.0.70
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: virt-handler-h7lj5
      namespace: harvester-system
      resourceVersion: "7320"
      uid: afbf0b2d-2344-45d0-a4c5-f14054ed7d1e
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2022-03-06T22:52:50Z"
    generateName: kubevirt-prometheus-metrics-
    generation: 18
    labels:
      app.kubernetes.io/component: kubevirt
      app.kubernetes.io/managed-by: kubevirt-operator
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: kubevirt-prometheus-metrics
      kubevirt.io: "null"
      prometheus.kubevirt.io: "null"
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:kubernetes.io/service-name: {}
            f:kubevirt.io: {}
            f:prometheus.kubevirt.io: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"96563f55-5d48-47fc-8ef2-89b105fbf041"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:56Z"
    name: kubevirt-prometheus-metrics-qs5wm
    namespace: harvester-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: kubevirt-prometheus-metrics
      uid: 96563f55-5d48-47fc-8ef2-89b105fbf041
    resourceVersion: "1026183"
    uid: facdb341-0aa2-4ec6-9849-958b385a5f91
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.66
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: virt-api-86455cdb7d-mdk4m
      namespace: harvester-system
      resourceVersion: "6189"
      uid: 7a98124d-1ba4-4711-a391-7225c655f9f2
  - addresses:
    - 10.52.0.67
    conditions:
      ready: true
    nodeName: node1
    targetRef:
      kind: Pod
      name: virt-api-86455cdb7d-khcv5
      namespace: harvester-system
      resourceVersion: "6181"
      uid: 326c914e-4e0d-461b-b3fc-87af92bafd1f
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:53:20Z"
    creationTimestamp: "2022-03-06T22:52:50Z"
    generateName: virt-api-
    generation: 5
    labels:
      app.kubernetes.io/component: kubevirt
      app.kubernetes.io/managed-by: kubevirt-operator
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: virt-api
      kubevirt.io: virt-api
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:kubernetes.io/service-name: {}
            f:kubevirt.io: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"c647b04d-5b8d-4deb-bab7-76a7573f562e"}:
              .: {}
              f:apiVersion: {}
              f:blockOwnerDeletion: {}
              f:controller: {}
              f:kind: {}
              f:name: {}
              f:uid: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:53:20Z"
    name: virt-api-z69sc
    namespace: harvester-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: virt-api
      uid: c647b04d-5b8d-4deb-bab7-76a7573f562e
    resourceVersion: "6194"
    uid: cabd6522-14dd-42a3-904c-5930e06e0f31
  ports:
  - name: "null"
    port: 8443
    protocol: TCP
kind: List
metadata:
  resourceVersion: "14659188"
