apiVersion: v1
items:
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: cluster-register
    usage:
      cpu: 2251747n
      memory: 58324Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:49:49Z"
    labels:
      app: cattle-cluster-agent
      pod-template-hash: 6df46b7b5c
    name: cattle-cluster-agent-6df46b7b5c-k4kqv
    namespace: cattle-system
  timestamp: "2022-03-22T23:48:54Z"
  window: 58s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: httpd
    usage:
      cpu: "0"
      memory: 9420Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:49:49Z"
    labels:
      app: harvester-cluster-repo
      pod-template-hash: 54b6486849
    name: harvester-cluster-repo-54b6486849-pjjbp
    namespace: cattle-system
  timestamp: "2022-03-22T23:49:03Z"
  window: 1m12s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: rancher
    usage:
      cpu: 247134019n
      memory: 755340Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:49:49Z"
    labels:
      app: rancher
      pod-template-hash: 775b48bfd
      release: rancher
    name: rancher-775b48bfd-shxsh
    namespace: cattle-system
  timestamp: "2022-03-22T23:49:02Z"
  window: 59s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: rancher-webhook
    usage:
      cpu: 967966n
      memory: 112696Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:49:49Z"
    labels:
      app: rancher-webhook
      pod-template-hash: 7c9c5cc887
    name: rancher-webhook-7c9c5cc887-kf7bw
    namespace: cattle-system
  timestamp: "2022-03-22T23:48:53Z"
  window: 1m0s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: system-upgrade-controller
    usage:
      cpu: 1752226n
      memory: 29968Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:49:49Z"
    labels:
      pod-template-hash: 5b6457d644
      upgrade.cattle.io/controller: system-upgrade-controller
    name: system-upgrade-controller-5b6457d644-x89x9
    namespace: cattle-system
  timestamp: "2022-03-22T23:49:00Z"
  window: 1m11s
kind: List
metadata: {}
