apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:50:37Z"
    labels:
      app.kubernetes.io/component: apiserver
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: harvester
      app.kubernetes.io/part-of: harvester
      app.kubernetes.io/version: 0.1.x
      helm.sh/chart: harvester-0.0.0-dev
      helm.sh/release: harvester
      kubernetes.io/cluster-service: "true"
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:helm.sh/release: {}
            f:kubernetes.io/cluster-service: {}
            f:objectset.rio.cattle.io/hash: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:06Z"
    name: harvester
    namespace: harvester-system
    resourceVersion: "1025034"
    uid: ffe72f98-090b-4d53-b38a-a173f3141cb8
  subsets:
  - addresses:
    - ip: 10.52.0.38
      nodeName: node1
      targetRef:
        kind: Pod
        name: harvester-d544ddb6f-6g2fl
        namespace: harvester-system
        resourceVersion: "4096"
        uid: fd0be963-a9d7-43cc-ba33-755951faefaa
    ports:
    - name: https
      port: 8443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:50:37Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
            f:objectset.rio.cattle.io/hash: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:06Z"
    name: harvester-webhook
    namespace: harvester-system
    resourceVersion: "1025059"
    uid: 3220e712-d0e6-46bd-876b-227271b0373b
  subsets:
  - addresses:
    - ip: 10.52.0.26
      nodeName: node1
      targetRef:
        kind: Pod
        name: harvester-webhook-67744f845f-5msj8
        namespace: harvester-system
        resourceVersion: "4073"
        uid: feb4b9e8-7f24-4fce-a106-2e57e147e4c1
    ports:
    - name: https
      port: 9443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:52:50Z"
    creationTimestamp: "2022-03-06T22:52:50Z"
    labels:
      app.kubernetes.io/component: kubevirt
      app.kubernetes.io/managed-by: kubevirt-operator
      kubevirt.io: "null"
      prometheus.kubevirt.io: "null"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:kubevirt.io: {}
            f:prometheus.kubevirt.io: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:52:50Z"
    name: kubevirt-operator-webhook
    namespace: harvester-system
    resourceVersion: "5752"
    uid: 07781d63-ae8e-499a-b38c-4d4fa5b7a986
  subsets:
  - addresses:
    - ip: 10.52.0.34
      nodeName: node1
      targetRef:
        kind: Pod
        name: virt-operator-56c5bdc7b8-jqntd
        namespace: harvester-system
        resourceVersion: "4895"
        uid: d1bc3106-d8c7-4169-93ac-b175c18eecc4
    ports:
    - name: webhooks
      port: 8444
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2022-03-06T22:52:50Z"
    labels:
      app.kubernetes.io/component: kubevirt
      app.kubernetes.io/managed-by: kubevirt-operator
      kubevirt.io: "null"
      prometheus.kubevirt.io: "null"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:kubevirt.io: {}
            f:prometheus.kubevirt.io: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-08T00:38:56Z"
    name: kubevirt-prometheus-metrics
    namespace: harvester-system
    resourceVersion: "1026185"
    uid: 18abb7dc-fb2e-4b63-8b92-e83911cab4cb
  subsets:
  - addresses:
    - ip: 10.52.0.34
      nodeName: node1
      targetRef:
        kind: Pod
        name: virt-operator-56c5bdc7b8-jqntd
        namespace: harvester-system
        resourceVersion: "4895"
        uid: d1bc3106-d8c7-4169-93ac-b175c18eecc4
    - ip: 10.52.0.66
      nodeName: node1
      targetRef:
        kind: Pod
        name: virt-api-86455cdb7d-mdk4m
        namespace: harvester-system
        resourceVersion: "6189"
        uid: 7a98124d-1ba4-4711-a391-7225c655f9f2
    - ip: 10.52.0.67
      nodeName: node1
      targetRef:
        kind: Pod
        name: virt-api-86455cdb7d-khcv5
        namespace: harvester-system
        resourceVersion: "6181"
        uid: 326c914e-4e0d-461b-b3fc-87af92bafd1f
    - ip: 10.52.0.70
      nodeName: node1
      targetRef:
        kind: Pod
        name: virt-handler-h7lj5
        namespace: harvester-system
        resourceVersion: "7320"
        uid: afbf0b2d-2344-45d0-a4c5-f14054ed7d1e
    - ip: 10.52.0.71
      nodeName: node1
      targetRef:
        kind: Pod
        name: virt-controller-5f649999dd-j5qpd
        namespace: harvester-system
        resourceVersion: "6847"
        uid: 76c4f877-c8cd-4925-9145-fb8b8f365d9a
    - ip: 10.52.0.72
      nodeName: node1
      targetRef:
        kind: Pod
        name: virt-controller-5f649999dd-5lw26
        namespace: harvester-system
        resourceVersion: "6853"
        uid: 222e8519-621a-4c66-9cff-5e6ea45d012c
    ports:
    - name: metrics
      port: 8443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2022-03-06T22:53:20Z"
    creationTimestamp: "2022-03-06T22:52:50Z"
    labels:
      app.kubernetes.io/component: kubevirt
      app.kubernetes.io/managed-by: kubevirt-operator
      kubevirt.io: virt-api
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:kubevirt.io: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-03-06T22:53:20Z"
    name: virt-api
    namespace: harvester-system
    resourceVersion: "6195"
    uid: 3ac5a0e5-b880-4772-ae49-5470f775b03e
  subsets:
  - addresses:
    - ip: 10.52.0.66
      nodeName: node1
      targetRef:
        kind: Pod
        name: virt-api-86455cdb7d-mdk4m
        namespace: harvester-system
        resourceVersion: "6189"
        uid: 7a98124d-1ba4-4711-a391-7225c655f9f2
    - ip: 10.52.0.67
      nodeName: node1
      targetRef:
        kind: Pod
        name: virt-api-86455cdb7d-khcv5
        namespace: harvester-system
        resourceVersion: "6181"
        uid: 326c914e-4e0d-461b-b3fc-87af92bafd1f
    ports:
    - port: 8443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"virt-controller-5f649999dd-5lw26","leaseDurationSeconds":15,"acquireTime":"2022-03-06T22:53:45Z","renewTime":"2022-03-22T23:50:00Z","leaderTransitions":0}'
    creationTimestamp: "2022-03-06T22:53:45Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:control-plane.alpha.kubernetes.io/leader: {}
      manager: virt-controller
      operation: Update
      time: "2022-03-06T22:53:45Z"
    name: virt-controller
    namespace: harvester-system
    resourceVersion: "14659177"
    uid: e77a5ddc-0d0a-4ad7-9641-cbcabb043036
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"virt-operator-56c5bdc7b8-jqntd","leaseDurationSeconds":15,"acquireTime":"2022-03-06T22:52:11Z","renewTime":"2022-03-22T23:50:00Z","leaderTransitions":0}'
    creationTimestamp: "2022-03-06T22:52:11Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:control-plane.alpha.kubernetes.io/leader: {}
      manager: virt-operator
      operation: Update
      time: "2022-03-06T22:52:11Z"
    name: virt-operator
    namespace: harvester-system
    resourceVersion: "14659169"
    uid: 896f60f9-5561-4303-a230-1b16b2e2b36f
kind: List
metadata:
  resourceVersion: "14659186"
