apiVersion: v1
items:
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: backing-image-manager
    usage:
      cpu: 639459n
      memory: 23244Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      longhorn.io/component: backing-image-manager
      longhorn.io/disk-uuid: a3c70e08-bfc1-4915-927a-8a6b80cc12b4
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: node1
    name: backing-image-manager-c00e-a3c7
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:56Z"
  window: 1m1s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-attacher
    usage:
      cpu: 279854n
      memory: 17744Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-attacher
      pod-template-hash: 66fcbbff5c
    name: csi-attacher-66fcbbff5c-drjmf
    namespace: longhorn-system
  timestamp: "2022-03-22T23:49:01Z"
  window: 1m3s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-attacher
    usage:
      cpu: 464657n
      memory: 16728Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-attacher
      pod-template-hash: 66fcbbff5c
    name: csi-attacher-66fcbbff5c-h72z5
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:56Z"
  window: 1m0s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-attacher
    usage:
      cpu: 936144n
      memory: 23408Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-attacher
      pod-template-hash: 66fcbbff5c
    name: csi-attacher-66fcbbff5c-qjcrr
    namespace: longhorn-system
  timestamp: "2022-03-22T23:49:03Z"
  window: 1m9s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-provisioner
    usage:
      cpu: 975398n
      memory: 15356Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-provisioner
      pod-template-hash: 84fcfbf785
    name: csi-provisioner-84fcfbf785-d5pbx
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:53Z"
  window: 1m1s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-provisioner
    usage:
      cpu: 1038721n
      memory: 17516Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-provisioner
      pod-template-hash: 84fcfbf785
    name: csi-provisioner-84fcfbf785-q4clc
    namespace: longhorn-system
  timestamp: "2022-03-22T23:49:02Z"
  window: 1m8s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-provisioner
    usage:
      cpu: 1413443n
      memory: 21304Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-provisioner
      pod-template-hash: 84fcfbf785
    name: csi-provisioner-84fcfbf785-tqz2w
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:59Z"
  window: 1m3s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-resizer
    usage:
      cpu: 243489n
      memory: 19420Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-resizer
      pod-template-hash: 558f9d8df
    name: csi-resizer-558f9d8df-69txc
    namespace: longhorn-system
  timestamp: "2022-03-22T23:49:00Z"
  window: 1m4s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-resizer
    usage:
      cpu: 1063372n
      memory: 23108Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-resizer
      pod-template-hash: 558f9d8df
    name: csi-resizer-558f9d8df-8swq7
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:53Z"
  window: 54s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-resizer
    usage:
      cpu: 229948n
      memory: 19504Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-resizer
      pod-template-hash: 558f9d8df
    name: csi-resizer-558f9d8df-mz4x6
    namespace: longhorn-system
  timestamp: "2022-03-22T23:49:02Z"
  window: 58s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-snapshotter
    usage:
      cpu: 1392068n
      memory: 16932Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-snapshotter
      pod-template-hash: 7dc99d7f87
    name: csi-snapshotter-7dc99d7f87-5tbwz
    namespace: longhorn-system
  timestamp: "2022-03-22T23:49:02Z"
  window: 1m13s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-snapshotter
    usage:
      cpu: 655886n
      memory: 14500Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-snapshotter
      pod-template-hash: 7dc99d7f87
    name: csi-snapshotter-7dc99d7f87-ggbk7
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:45Z"
  window: 45s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-snapshotter
    usage:
      cpu: 866801n
      memory: 15940Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: csi-snapshotter
      pod-template-hash: 7dc99d7f87
    name: csi-snapshotter-7dc99d7f87-sr54m
    namespace: longhorn-system
  timestamp: "2022-03-22T23:49:02Z"
  window: 58s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: engine-image-ei-fa2dfbf0
    usage:
      cpu: 15706983n
      memory: 21916Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      controller-revision-hash: 69bcc4b59
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-fa2dfbf0
      pod-template-generation: "1"
    name: engine-image-ei-fa2dfbf0-n44gc
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:59Z"
  window: 59s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: engine-manager
    usage:
      cpu: 309103n
      memory: 26788Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      longhorn.io/component: instance-manager
      longhorn.io/instance-manager-image: imi-2ff8743e
      longhorn.io/instance-manager-type: engine
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: node1
    name: instance-manager-e-5708ef52
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:52Z"
  window: 54s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: replica-manager
    usage:
      cpu: 449424n
      memory: 25640Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      longhorn.io/component: instance-manager
      longhorn.io/instance-manager-image: imi-2ff8743e
      longhorn.io/instance-manager-type: replica
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: node1
    name: instance-manager-r-9d910deb
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:50Z"
  window: 55s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: node-driver-registrar
    usage:
      cpu: 28998n
      memory: 10800Ki
  - name: longhorn-csi-plugin
    usage:
      cpu: 405088n
      memory: 19896Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: longhorn-csi-plugin
      controller-revision-hash: 558c787657
      pod-template-generation: "1"
    name: longhorn-csi-plugin-qqvbx
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:52Z"
  window: 1m1s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-driver-deployer
    usage:
      cpu: 47930n
      memory: 13864Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: longhorn-driver-deployer
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.2.3
      helm.sh/chart: longhorn-1.2.3
      pod-template-hash: 7769758bc9
    name: longhorn-driver-deployer-7769758bc9-m5kqw
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:56Z"
  window: 59s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-manager
    usage:
      cpu: 17794143n
      memory: 53932Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: longhorn-manager
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.2.3
      controller-revision-hash: 6c8b7bb8dd
      helm.sh/chart: longhorn-1.2.3
      pod-template-generation: "1"
    name: longhorn-manager-pmjr9
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:51Z"
  window: 53s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-ui
    usage:
      cpu: "0"
      memory: 3608Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2022-03-22T23:50:05Z"
    labels:
      app: longhorn-ui
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.2.3
      helm.sh/chart: longhorn-1.2.3
      pod-template-hash: 8466bcb8b7
    name: longhorn-ui-8466bcb8b7-rm9v9
    namespace: longhorn-system
  timestamp: "2022-03-22T23:48:50Z"
  window: 57s
kind: List
metadata: {}
