apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yOTW6sMBCE79Lr8Tz8mJAZLpALZBexaJuCcWRs5G4iRYi7R4CUZZb1o69qpQnKPStTuxKnlJU15CS7zO4TXgV6LSFfPatGXEP+F3pqaYiAGpezihaezcHYLuQLDsJ7mCDK00xtWmK8UGSH+Cf3yfKklm4vtqqrerAP13jHg39UtbW3u7P3phls4/87vDIfa4kn/J7hEUnNCDW+oKczlZn9XjlnzNn0cRFFESPfoph2UlkihNqPlXgObyUv866IugsVSF6KP2IS+AKV3f9CcYc3Qqnbuu0nAAD//98usAtOAQAA
      objectset.rio.cattle.io/id: fleet-bootstrap-data
    creationTimestamp: "2022-03-06T22:49:12Z"
    labels:
      objectset.rio.cattle.io/hash: 4510303f19b6cbafc9031148b1866f16c2be7aaa
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
        f:rules: {}
      manager: fleetcontroller
      operation: Update
      time: "2022-03-06T22:49:12Z"
    name: fleet-agent-get-cred
    namespace: cattle-fleet-clusters-system
    resourceVersion: "1708"
    uid: efc9fc46-27d9-49bf-9656-18702a80fcfc
  rules:
  - apiGroups:
    - "null"
    resources:
    - secrets
    verbs:
    - get
kind: List
metadata:
  resourceVersion: "14659096"
